// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: agent_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sentinel_Register_FullMethodName            = "/sentinel.Sentinel/Register"
	Sentinel_Heartbeat_FullMethodName           = "/sentinel.Sentinel/Heartbeat"
	Sentinel_ReportEvents_FullMethodName        = "/sentinel.Sentinel/ReportEvents"
	Sentinel_GetProbeList_FullMethodName        = "/sentinel.Sentinel/GetProbeList"
	Sentinel_ReportShutdown_FullMethodName      = "/sentinel.Sentinel/ReportShutdown"
	Sentinel_ReportProcesses_FullMethodName     = "/sentinel.Sentinel/ReportProcesses"
	Sentinel_ReportUsers_FullMethodName         = "/sentinel.Sentinel/ReportUsers"
	Sentinel_ReportSystemInfo_FullMethodName    = "/sentinel.Sentinel/ReportSystemInfo"
	Sentinel_ReportPackages_FullMethodName      = "/sentinel.Sentinel/ReportPackages"
	Sentinel_ReportCronJobs_FullMethodName      = "/sentinel.Sentinel/ReportCronJobs"
	Sentinel_ReportServices_FullMethodName      = "/sentinel.Sentinel/ReportServices"
	Sentinel_ReportWebComponents_FullMethodName = "/sentinel.Sentinel/ReportWebComponents"
	Sentinel_ReportHardware_FullMethodName      = "/sentinel.Sentinel/ReportHardware"
	Sentinel_ReportNetwork_FullMethodName       = "/sentinel.Sentinel/ReportNetwork"
	Sentinel_ReportPerformance_FullMethodName   = "/sentinel.Sentinel/ReportPerformance"
	Sentinel_ReportAgentSelf_FullMethodName     = "/sentinel.Sentinel/ReportAgentSelf"
)

// SentinelClient is the client API for Sentinel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SentinelClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	ReportEvents(ctx context.Context, in *EventReport, opts ...grpc.CallOption) (*ReportResponse, error)
	GetProbeList(ctx context.Context, in *ProbeListRequest, opts ...grpc.CallOption) (*ProbeListResponse, error)
	ReportShutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	// 资产上报
	ReportProcesses(ctx context.Context, in *ProcessReport, opts ...grpc.CallOption) (*ReportResponse, error)
	ReportUsers(ctx context.Context, in *UserReport, opts ...grpc.CallOption) (*ReportResponse, error)
	ReportSystemInfo(ctx context.Context, in *SystemReport, opts ...grpc.CallOption) (*ReportResponse, error)
	ReportPackages(ctx context.Context, in *PackageReport, opts ...grpc.CallOption) (*ReportResponse, error)
	ReportCronJobs(ctx context.Context, in *CronReport, opts ...grpc.CallOption) (*ReportResponse, error)
	ReportServices(ctx context.Context, in *ServiceReport, opts ...grpc.CallOption) (*ReportResponse, error)
	ReportWebComponents(ctx context.Context, in *WebComponentReport, opts ...grpc.CallOption) (*ReportResponse, error)
	ReportHardware(ctx context.Context, in *HardwareReport, opts ...grpc.CallOption) (*ReportResponse, error)
	ReportNetwork(ctx context.Context, in *NetworkReport, opts ...grpc.CallOption) (*ReportResponse, error)
	ReportPerformance(ctx context.Context, in *PerfReport, opts ...grpc.CallOption) (*ReportResponse, error)
	ReportAgentSelf(ctx context.Context, in *AgentSelfReport, opts ...grpc.CallOption) (*ReportResponse, error)
}

type sentinelClient struct {
	cc grpc.ClientConnInterface
}

func NewSentinelClient(cc grpc.ClientConnInterface) SentinelClient {
	return &sentinelClient{cc}
}

func (c *sentinelClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, Sentinel_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, Sentinel_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelClient) ReportEvents(ctx context.Context, in *EventReport, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, Sentinel_ReportEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelClient) GetProbeList(ctx context.Context, in *ProbeListRequest, opts ...grpc.CallOption) (*ProbeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeListResponse)
	err := c.cc.Invoke(ctx, Sentinel_GetProbeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelClient) ReportShutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, Sentinel_ReportShutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelClient) ReportProcesses(ctx context.Context, in *ProcessReport, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, Sentinel_ReportProcesses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelClient) ReportUsers(ctx context.Context, in *UserReport, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, Sentinel_ReportUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelClient) ReportSystemInfo(ctx context.Context, in *SystemReport, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, Sentinel_ReportSystemInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelClient) ReportPackages(ctx context.Context, in *PackageReport, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, Sentinel_ReportPackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelClient) ReportCronJobs(ctx context.Context, in *CronReport, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, Sentinel_ReportCronJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelClient) ReportServices(ctx context.Context, in *ServiceReport, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, Sentinel_ReportServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelClient) ReportWebComponents(ctx context.Context, in *WebComponentReport, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, Sentinel_ReportWebComponents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelClient) ReportHardware(ctx context.Context, in *HardwareReport, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, Sentinel_ReportHardware_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelClient) ReportNetwork(ctx context.Context, in *NetworkReport, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, Sentinel_ReportNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelClient) ReportPerformance(ctx context.Context, in *PerfReport, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, Sentinel_ReportPerformance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelClient) ReportAgentSelf(ctx context.Context, in *AgentSelfReport, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, Sentinel_ReportAgentSelf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SentinelServer is the server API for Sentinel service.
// All implementations must embed UnimplementedSentinelServer
// for forward compatibility.
type SentinelServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	ReportEvents(context.Context, *EventReport) (*ReportResponse, error)
	GetProbeList(context.Context, *ProbeListRequest) (*ProbeListResponse, error)
	ReportShutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	// 资产上报
	ReportProcesses(context.Context, *ProcessReport) (*ReportResponse, error)
	ReportUsers(context.Context, *UserReport) (*ReportResponse, error)
	ReportSystemInfo(context.Context, *SystemReport) (*ReportResponse, error)
	ReportPackages(context.Context, *PackageReport) (*ReportResponse, error)
	ReportCronJobs(context.Context, *CronReport) (*ReportResponse, error)
	ReportServices(context.Context, *ServiceReport) (*ReportResponse, error)
	ReportWebComponents(context.Context, *WebComponentReport) (*ReportResponse, error)
	ReportHardware(context.Context, *HardwareReport) (*ReportResponse, error)
	ReportNetwork(context.Context, *NetworkReport) (*ReportResponse, error)
	ReportPerformance(context.Context, *PerfReport) (*ReportResponse, error)
	ReportAgentSelf(context.Context, *AgentSelfReport) (*ReportResponse, error)
	mustEmbedUnimplementedSentinelServer()
}

// UnimplementedSentinelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSentinelServer struct{}

func (UnimplementedSentinelServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedSentinelServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedSentinelServer) ReportEvents(context.Context, *EventReport) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportEvents not implemented")
}
func (UnimplementedSentinelServer) GetProbeList(context.Context, *ProbeListRequest) (*ProbeListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProbeList not implemented")
}
func (UnimplementedSentinelServer) ReportShutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportShutdown not implemented")
}
func (UnimplementedSentinelServer) ReportProcesses(context.Context, *ProcessReport) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportProcesses not implemented")
}
func (UnimplementedSentinelServer) ReportUsers(context.Context, *UserReport) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportUsers not implemented")
}
func (UnimplementedSentinelServer) ReportSystemInfo(context.Context, *SystemReport) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportSystemInfo not implemented")
}
func (UnimplementedSentinelServer) ReportPackages(context.Context, *PackageReport) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportPackages not implemented")
}
func (UnimplementedSentinelServer) ReportCronJobs(context.Context, *CronReport) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportCronJobs not implemented")
}
func (UnimplementedSentinelServer) ReportServices(context.Context, *ServiceReport) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportServices not implemented")
}
func (UnimplementedSentinelServer) ReportWebComponents(context.Context, *WebComponentReport) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportWebComponents not implemented")
}
func (UnimplementedSentinelServer) ReportHardware(context.Context, *HardwareReport) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportHardware not implemented")
}
func (UnimplementedSentinelServer) ReportNetwork(context.Context, *NetworkReport) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportNetwork not implemented")
}
func (UnimplementedSentinelServer) ReportPerformance(context.Context, *PerfReport) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportPerformance not implemented")
}
func (UnimplementedSentinelServer) ReportAgentSelf(context.Context, *AgentSelfReport) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportAgentSelf not implemented")
}
func (UnimplementedSentinelServer) mustEmbedUnimplementedSentinelServer() {}
func (UnimplementedSentinelServer) testEmbeddedByValue()                  {}

// UnsafeSentinelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SentinelServer will
// result in compilation errors.
type UnsafeSentinelServer interface {
	mustEmbedUnimplementedSentinelServer()
}

func RegisterSentinelServer(s grpc.ServiceRegistrar, srv SentinelServer) {
	// If the following call panics, it indicates UnimplementedSentinelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sentinel_ServiceDesc, srv)
}

func _Sentinel_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sentinel_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sentinel_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sentinel_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sentinel_ReportEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelServer).ReportEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sentinel_ReportEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelServer).ReportEvents(ctx, req.(*EventReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sentinel_GetProbeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelServer).GetProbeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sentinel_GetProbeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelServer).GetProbeList(ctx, req.(*ProbeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sentinel_ReportShutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelServer).ReportShutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sentinel_ReportShutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelServer).ReportShutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sentinel_ReportProcesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelServer).ReportProcesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sentinel_ReportProcesses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelServer).ReportProcesses(ctx, req.(*ProcessReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sentinel_ReportUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelServer).ReportUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sentinel_ReportUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelServer).ReportUsers(ctx, req.(*UserReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sentinel_ReportSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelServer).ReportSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sentinel_ReportSystemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelServer).ReportSystemInfo(ctx, req.(*SystemReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sentinel_ReportPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelServer).ReportPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sentinel_ReportPackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelServer).ReportPackages(ctx, req.(*PackageReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sentinel_ReportCronJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CronReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelServer).ReportCronJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sentinel_ReportCronJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelServer).ReportCronJobs(ctx, req.(*CronReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sentinel_ReportServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelServer).ReportServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sentinel_ReportServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelServer).ReportServices(ctx, req.(*ServiceReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sentinel_ReportWebComponents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebComponentReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelServer).ReportWebComponents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sentinel_ReportWebComponents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelServer).ReportWebComponents(ctx, req.(*WebComponentReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sentinel_ReportHardware_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HardwareReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelServer).ReportHardware(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sentinel_ReportHardware_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelServer).ReportHardware(ctx, req.(*HardwareReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sentinel_ReportNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelServer).ReportNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sentinel_ReportNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelServer).ReportNetwork(ctx, req.(*NetworkReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sentinel_ReportPerformance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PerfReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelServer).ReportPerformance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sentinel_ReportPerformance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelServer).ReportPerformance(ctx, req.(*PerfReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sentinel_ReportAgentSelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentSelfReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelServer).ReportAgentSelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sentinel_ReportAgentSelf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelServer).ReportAgentSelf(ctx, req.(*AgentSelfReport))
	}
	return interceptor(ctx, in, info, handler)
}

// Sentinel_ServiceDesc is the grpc.ServiceDesc for Sentinel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sentinel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sentinel.Sentinel",
	HandlerType: (*SentinelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Sentinel_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Sentinel_Heartbeat_Handler,
		},
		{
			MethodName: "ReportEvents",
			Handler:    _Sentinel_ReportEvents_Handler,
		},
		{
			MethodName: "GetProbeList",
			Handler:    _Sentinel_GetProbeList_Handler,
		},
		{
			MethodName: "ReportShutdown",
			Handler:    _Sentinel_ReportShutdown_Handler,
		},
		{
			MethodName: "ReportProcesses",
			Handler:    _Sentinel_ReportProcesses_Handler,
		},
		{
			MethodName: "ReportUsers",
			Handler:    _Sentinel_ReportUsers_Handler,
		},
		{
			MethodName: "ReportSystemInfo",
			Handler:    _Sentinel_ReportSystemInfo_Handler,
		},
		{
			MethodName: "ReportPackages",
			Handler:    _Sentinel_ReportPackages_Handler,
		},
		{
			MethodName: "ReportCronJobs",
			Handler:    _Sentinel_ReportCronJobs_Handler,
		},
		{
			MethodName: "ReportServices",
			Handler:    _Sentinel_ReportServices_Handler,
		},
		{
			MethodName: "ReportWebComponents",
			Handler:    _Sentinel_ReportWebComponents_Handler,
		},
		{
			MethodName: "ReportHardware",
			Handler:    _Sentinel_ReportHardware_Handler,
		},
		{
			MethodName: "ReportNetwork",
			Handler:    _Sentinel_ReportNetwork_Handler,
		},
		{
			MethodName: "ReportPerformance",
			Handler:    _Sentinel_ReportPerformance_Handler,
		},
		{
			MethodName: "ReportAgentSelf",
			Handler:    _Sentinel_ReportAgentSelf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent_service.proto",
}
