// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.12.4
// source: common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProbeCommand_CommandType int32

const (
	ProbeCommand_LOAD      ProbeCommand_CommandType = 0
	ProbeCommand_UNLOAD    ProbeCommand_CommandType = 1
	ProbeCommand_RELOAD    ProbeCommand_CommandType = 3
	ProbeCommand_INSTALL   ProbeCommand_CommandType = 4
	ProbeCommand_COLLECT   ProbeCommand_CommandType = 5
	ProbeCommand_SET_GROUP ProbeCommand_CommandType = 6
)

// Enum value maps for ProbeCommand_CommandType.
var (
	ProbeCommand_CommandType_name = map[int32]string{
		0: "LOAD",
		1: "UNLOAD",
		3: "RELOAD",
		4: "INSTALL",
		5: "COLLECT",
		6: "SET_GROUP",
	}
	ProbeCommand_CommandType_value = map[string]int32{
		"LOAD":      0,
		"UNLOAD":    1,
		"RELOAD":    3,
		"INSTALL":   4,
		"COLLECT":   5,
		"SET_GROUP": 6,
	}
)

func (x ProbeCommand_CommandType) Enum() *ProbeCommand_CommandType {
	p := new(ProbeCommand_CommandType)
	*p = x
	return p
}

func (x ProbeCommand_CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProbeCommand_CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (ProbeCommand_CommandType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x ProbeCommand_CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProbeCommand_CommandType.Descriptor instead.
func (ProbeCommand_CommandType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1, 0}
}

// ReportResponse 是所有上报类 RPC 的通用响应
type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *ReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ProbeCommand 下发命令（心跳响应中携带）
type ProbeCommand struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Type          ProbeCommand_CommandType `protobuf:"varint,1,opt,name=type,proto3,enum=sentinel.ProbeCommand_CommandType" json:"type,omitempty"`
	ProbeId       string                   `protobuf:"bytes,2,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	ProbeName     string                   `protobuf:"bytes,3,opt,name=probe_name,json=probeName,proto3" json:"probe_name,omitempty"`
	ProbeData     []byte                   `protobuf:"bytes,4,opt,name=probe_data,json=probeData,proto3" json:"probe_data,omitempty"`
	ProbeConfig   string                   `protobuf:"bytes,5,opt,name=probe_config,json=probeConfig,proto3" json:"probe_config,omitempty"`
	GroupName     string                   `protobuf:"bytes,6,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeCommand) Reset() {
	*x = ProbeCommand{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeCommand) ProtoMessage() {}

func (x *ProbeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeCommand.ProtoReflect.Descriptor instead.
func (*ProbeCommand) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *ProbeCommand) GetType() ProbeCommand_CommandType {
	if x != nil {
		return x.Type
	}
	return ProbeCommand_LOAD
}

func (x *ProbeCommand) GetProbeId() string {
	if x != nil {
		return x.ProbeId
	}
	return ""
}

func (x *ProbeCommand) GetProbeName() string {
	if x != nil {
		return x.ProbeName
	}
	return ""
}

func (x *ProbeCommand) GetProbeData() []byte {
	if x != nil {
		return x.ProbeData
	}
	return nil
}

func (x *ProbeCommand) GetProbeConfig() string {
	if x != nil {
		return x.ProbeConfig
	}
	return ""
}

func (x *ProbeCommand) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\bsentinel\"D\n" +
	"\x0eReportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xbb\x02\n" +
	"\fProbeCommand\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".sentinel.ProbeCommand.CommandTypeR\x04type\x12\x19\n" +
	"\bprobe_id\x18\x02 \x01(\tR\aprobeId\x12\x1d\n" +
	"\n" +
	"probe_name\x18\x03 \x01(\tR\tprobeName\x12\x1d\n" +
	"\n" +
	"probe_data\x18\x04 \x01(\fR\tprobeData\x12!\n" +
	"\fprobe_config\x18\x05 \x01(\tR\vprobeConfig\x12\x1d\n" +
	"\n" +
	"group_name\x18\x06 \x01(\tR\tgroupName\"X\n" +
	"\vCommandType\x12\b\n" +
	"\x04LOAD\x10\x00\x12\n" +
	"\n" +
	"\x06UNLOAD\x10\x01\x12\n" +
	"\n" +
	"\x06RELOAD\x10\x03\x12\v\n" +
	"\aINSTALL\x10\x04\x12\v\n" +
	"\aCOLLECT\x10\x05\x12\r\n" +
	"\tSET_GROUP\x10\x06B.Z,github.com/CoderXinNing/ebpf-system/proto/pbb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_goTypes = []any{
	(ProbeCommand_CommandType)(0), // 0: sentinel.ProbeCommand.CommandType
	(*ReportResponse)(nil),        // 1: sentinel.ReportResponse
	(*ProbeCommand)(nil),          // 2: sentinel.ProbeCommand
}
var file_common_proto_depIdxs = []int32{
	0, // 0: sentinel.ProbeCommand.type:type_name -> sentinel.ProbeCommand.CommandType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
