// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package guardian

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadGuardian returns the embedded CollectionSpec for guardian.
func loadGuardian() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_GuardianBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load guardian: %w", err)
	}

	return spec, err
}

// loadGuardianObjects loads guardian and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*guardianObjects
//	*guardianPrograms
//	*guardianMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadGuardianObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadGuardian()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// guardianSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type guardianSpecs struct {
	guardianProgramSpecs
	guardianMapSpecs
	guardianVariableSpecs
}

// guardianProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type guardianProgramSpecs struct {
	TraceBpfDelete *ebpf.ProgramSpec `ebpf:"trace_bpf_delete"`
	TraceKill      *ebpf.ProgramSpec `ebpf:"trace_kill"`
	TracePtrace    *ebpf.ProgramSpec `ebpf:"trace_ptrace"`
}

// guardianMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type guardianMapSpecs struct {
	AgentConfig *ebpf.MapSpec `ebpf:"agent_config"`
	Alerts      *ebpf.MapSpec `ebpf:"alerts"`
}

// guardianVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type guardianVariableSpecs struct {
}

// guardianObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadGuardianObjects or ebpf.CollectionSpec.LoadAndAssign.
type guardianObjects struct {
	guardianPrograms
	guardianMaps
	guardianVariables
}

func (o *guardianObjects) Close() error {
	return _GuardianClose(
		&o.guardianPrograms,
		&o.guardianMaps,
	)
}

// guardianMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadGuardianObjects or ebpf.CollectionSpec.LoadAndAssign.
type guardianMaps struct {
	AgentConfig *ebpf.Map `ebpf:"agent_config"`
	Alerts      *ebpf.Map `ebpf:"alerts"`
}

func (m *guardianMaps) Close() error {
	return _GuardianClose(
		m.AgentConfig,
		m.Alerts,
	)
}

// guardianVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadGuardianObjects or ebpf.CollectionSpec.LoadAndAssign.
type guardianVariables struct {
}

// guardianPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadGuardianObjects or ebpf.CollectionSpec.LoadAndAssign.
type guardianPrograms struct {
	TraceBpfDelete *ebpf.Program `ebpf:"trace_bpf_delete"`
	TraceKill      *ebpf.Program `ebpf:"trace_kill"`
	TracePtrace    *ebpf.Program `ebpf:"trace_ptrace"`
}

func (p *guardianPrograms) Close() error {
	return _GuardianClose(
		p.TraceBpfDelete,
		p.TraceKill,
		p.TracePtrace,
	)
}

func _GuardianClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed guardian_bpfel.o
var _GuardianBytes []byte
