// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/agent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProbeCommand_CommandType int32

const (
	ProbeCommand_LOAD   ProbeCommand_CommandType = 0
	ProbeCommand_UNLOAD ProbeCommand_CommandType = 1
	ProbeCommand_UPDATE ProbeCommand_CommandType = 2
)

// Enum value maps for ProbeCommand_CommandType.
var (
	ProbeCommand_CommandType_name = map[int32]string{
		0: "LOAD",
		1: "UNLOAD",
		2: "UPDATE",
	}
	ProbeCommand_CommandType_value = map[string]int32{
		"LOAD":   0,
		"UNLOAD": 1,
		"UPDATE": 2,
	}
)

func (x ProbeCommand_CommandType) Enum() *ProbeCommand_CommandType {
	p := new(ProbeCommand_CommandType)
	*p = x
	return p
}

func (x ProbeCommand_CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProbeCommand_CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[0].Descriptor()
}

func (ProbeCommand_CommandType) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[0]
}

func (x ProbeCommand_CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProbeCommand_CommandType.Descriptor instead.
func (ProbeCommand_CommandType) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6, 0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	KernelVersion string                 `protobuf:"bytes,3,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	IpAddress     string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Framework     *FrameworkInfo         `protobuf:"bytes,5,opt,name=framework,proto3" json:"framework,omitempty"`
	KernelInfo    *KernelInfo            `protobuf:"bytes,6,opt,name=kernel_info,json=kernelInfo,proto3" json:"kernel_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *RegisterRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterRequest) GetFramework() *FrameworkInfo {
	if x != nil {
		return x.Framework
	}
	return nil
}

func (x *RegisterRequest) GetKernelInfo() *KernelInfo {
	if x != nil {
		return x.KernelInfo
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AgentToken    string                 `protobuf:"bytes,3,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

type FrameworkInfo struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	BccAvailable           bool                   `protobuf:"varint,1,opt,name=bcc_available,json=bccAvailable,proto3" json:"bcc_available,omitempty"`
	BccVersion             string                 `protobuf:"bytes,2,opt,name=bcc_version,json=bccVersion,proto3" json:"bcc_version,omitempty"`
	PythonBccAvailable     bool                   `protobuf:"varint,3,opt,name=python_bcc_available,json=pythonBccAvailable,proto3" json:"python_bcc_available,omitempty"`
	LibbpfAvailable        bool                   `protobuf:"varint,4,opt,name=libbpf_available,json=libbpfAvailable,proto3" json:"libbpf_available,omitempty"`
	LibbpfVersion          string                 `protobuf:"bytes,5,opt,name=libbpf_version,json=libbpfVersion,proto3" json:"libbpf_version,omitempty"`
	LibbpfCore             bool                   `protobuf:"varint,6,opt,name=libbpf_core,json=libbpfCore,proto3" json:"libbpf_core,omitempty"`
	BpftraceAvailable      bool                   `protobuf:"varint,7,opt,name=bpftrace_available,json=bpftraceAvailable,proto3" json:"bpftrace_available,omitempty"`
	BpftraceVersion        string                 `protobuf:"bytes,8,opt,name=bpftrace_version,json=bpftraceVersion,proto3" json:"bpftrace_version,omitempty"`
	ClangAvailable         bool                   `protobuf:"varint,9,opt,name=clang_available,json=clangAvailable,proto3" json:"clang_available,omitempty"`
	ClangVersion           string                 `protobuf:"bytes,10,opt,name=clang_version,json=clangVersion,proto3" json:"clang_version,omitempty"`
	LlvmAvailable          bool                   `protobuf:"varint,11,opt,name=llvm_available,json=llvmAvailable,proto3" json:"llvm_available,omitempty"`
	LlvmVersion            string                 `protobuf:"bytes,12,opt,name=llvm_version,json=llvmVersion,proto3" json:"llvm_version,omitempty"`
	KernelHeadersAvailable bool                   `protobuf:"varint,13,opt,name=kernel_headers_available,json=kernelHeadersAvailable,proto3" json:"kernel_headers_available,omitempty"`
	GoEbpfAvailable        bool                   `protobuf:"varint,14,opt,name=go_ebpf_available,json=goEbpfAvailable,proto3" json:"go_ebpf_available,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FrameworkInfo) Reset() {
	*x = FrameworkInfo{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameworkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameworkInfo) ProtoMessage() {}

func (x *FrameworkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameworkInfo.ProtoReflect.Descriptor instead.
func (*FrameworkInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *FrameworkInfo) GetBccAvailable() bool {
	if x != nil {
		return x.BccAvailable
	}
	return false
}

func (x *FrameworkInfo) GetBccVersion() string {
	if x != nil {
		return x.BccVersion
	}
	return ""
}

func (x *FrameworkInfo) GetPythonBccAvailable() bool {
	if x != nil {
		return x.PythonBccAvailable
	}
	return false
}

func (x *FrameworkInfo) GetLibbpfAvailable() bool {
	if x != nil {
		return x.LibbpfAvailable
	}
	return false
}

func (x *FrameworkInfo) GetLibbpfVersion() string {
	if x != nil {
		return x.LibbpfVersion
	}
	return ""
}

func (x *FrameworkInfo) GetLibbpfCore() bool {
	if x != nil {
		return x.LibbpfCore
	}
	return false
}

func (x *FrameworkInfo) GetBpftraceAvailable() bool {
	if x != nil {
		return x.BpftraceAvailable
	}
	return false
}

func (x *FrameworkInfo) GetBpftraceVersion() string {
	if x != nil {
		return x.BpftraceVersion
	}
	return ""
}

func (x *FrameworkInfo) GetClangAvailable() bool {
	if x != nil {
		return x.ClangAvailable
	}
	return false
}

func (x *FrameworkInfo) GetClangVersion() string {
	if x != nil {
		return x.ClangVersion
	}
	return ""
}

func (x *FrameworkInfo) GetLlvmAvailable() bool {
	if x != nil {
		return x.LlvmAvailable
	}
	return false
}

func (x *FrameworkInfo) GetLlvmVersion() string {
	if x != nil {
		return x.LlvmVersion
	}
	return ""
}

func (x *FrameworkInfo) GetKernelHeadersAvailable() bool {
	if x != nil {
		return x.KernelHeadersAvailable
	}
	return false
}

func (x *FrameworkInfo) GetGoEbpfAvailable() bool {
	if x != nil {
		return x.GoEbpfAvailable
	}
	return false
}

type KernelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	BtfEnabled    bool                   `protobuf:"varint,3,opt,name=btf_enabled,json=btfEnabled,proto3" json:"btf_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KernelInfo) Reset() {
	*x = KernelInfo{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelInfo) ProtoMessage() {}

func (x *KernelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelInfo.ProtoReflect.Descriptor instead.
func (*KernelInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *KernelInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *KernelInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *KernelInfo) GetBtfEnabled() bool {
	if x != nil {
		return x.BtfEnabled
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentToken    string                 `protobuf:"bytes,2,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ActiveProbes  int32                  `protobuf:"varint,4,opt,name=active_probes,json=activeProbes,proto3" json:"active_probes,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,5,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemBytes      int64                  `protobuf:"varint,6,opt,name=mem_bytes,json=memBytes,proto3" json:"mem_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetActiveProbes() int32 {
	if x != nil {
		return x.ActiveProbes
	}
	return 0
}

func (x *HeartbeatRequest) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *HeartbeatRequest) GetMemBytes() int64 {
	if x != nil {
		return x.MemBytes
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Commands      []*ProbeCommand        `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetCommands() []*ProbeCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

type ProbeCommand struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Type          ProbeCommand_CommandType `protobuf:"varint,1,opt,name=type,proto3,enum=sentinel.ProbeCommand_CommandType" json:"type,omitempty"`
	ProbeId       string                   `protobuf:"bytes,2,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	ProbeName     string                   `protobuf:"bytes,3,opt,name=probe_name,json=probeName,proto3" json:"probe_name,omitempty"`
	ProbeData     []byte                   `protobuf:"bytes,4,opt,name=probe_data,json=probeData,proto3" json:"probe_data,omitempty"`
	ConfigKeys    []string                 `protobuf:"bytes,5,rep,name=config_keys,json=configKeys,proto3" json:"config_keys,omitempty"`
	ConfigValues  []string                 `protobuf:"bytes,6,rep,name=config_values,json=configValues,proto3" json:"config_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeCommand) Reset() {
	*x = ProbeCommand{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeCommand) ProtoMessage() {}

func (x *ProbeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeCommand.ProtoReflect.Descriptor instead.
func (*ProbeCommand) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ProbeCommand) GetType() ProbeCommand_CommandType {
	if x != nil {
		return x.Type
	}
	return ProbeCommand_LOAD
}

func (x *ProbeCommand) GetProbeId() string {
	if x != nil {
		return x.ProbeId
	}
	return ""
}

func (x *ProbeCommand) GetProbeName() string {
	if x != nil {
		return x.ProbeName
	}
	return ""
}

func (x *ProbeCommand) GetProbeData() []byte {
	if x != nil {
		return x.ProbeData
	}
	return nil
}

func (x *ProbeCommand) GetConfigKeys() []string {
	if x != nil {
		return x.ConfigKeys
	}
	return nil
}

func (x *ProbeCommand) GetConfigValues() []string {
	if x != nil {
		return x.ConfigValues
	}
	return nil
}

type ProbeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProbeId       string                 `protobuf:"bytes,1,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	ProbeName     string                 `protobuf:"bytes,2,opt,name=probe_name,json=probeName,proto3" json:"probe_name,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Pid           int32                  `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`
	Comm          string                 `protobuf:"bytes,6,opt,name=comm,proto3" json:"comm,omitempty"`
	Filename      string                 `protobuf:"bytes,7,opt,name=filename,proto3" json:"filename,omitempty"`
	Details       string                 `protobuf:"bytes,8,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeEvent) Reset() {
	*x = ProbeEvent{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeEvent) ProtoMessage() {}

func (x *ProbeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeEvent.ProtoReflect.Descriptor instead.
func (*ProbeEvent) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ProbeEvent) GetProbeId() string {
	if x != nil {
		return x.ProbeId
	}
	return ""
}

func (x *ProbeEvent) GetProbeName() string {
	if x != nil {
		return x.ProbeName
	}
	return ""
}

func (x *ProbeEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ProbeEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ProbeEvent) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProbeEvent) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *ProbeEvent) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ProbeEvent) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type EventReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentToken    string                 `protobuf:"bytes,2,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	Events        []*ProbeEvent          `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventReport) Reset() {
	*x = EventReport{}
	mi := &file_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventReport) ProtoMessage() {}

func (x *EventReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventReport.ProtoReflect.Descriptor instead.
func (*EventReport) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *EventReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EventReport) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

func (x *EventReport) GetEvents() []*ProbeEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\bsentinel\"\xfc\x01\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12%\n" +
	"\x0ekernel_version\x18\x03 \x01(\tR\rkernelVersion\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x125\n" +
	"\tframework\x18\x05 \x01(\v2\x17.sentinel.FrameworkInfoR\tframework\x125\n" +
	"\vkernel_info\x18\x06 \x01(\v2\x14.sentinel.KernelInfoR\n" +
	"kernelInfo\"g\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vagent_token\x18\x03 \x01(\tR\n" +
	"agentToken\"\xd2\x04\n" +
	"\rFrameworkInfo\x12#\n" +
	"\rbcc_available\x18\x01 \x01(\bR\fbccAvailable\x12\x1f\n" +
	"\vbcc_version\x18\x02 \x01(\tR\n" +
	"bccVersion\x120\n" +
	"\x14python_bcc_available\x18\x03 \x01(\bR\x12pythonBccAvailable\x12)\n" +
	"\x10libbpf_available\x18\x04 \x01(\bR\x0flibbpfAvailable\x12%\n" +
	"\x0elibbpf_version\x18\x05 \x01(\tR\rlibbpfVersion\x12\x1f\n" +
	"\vlibbpf_core\x18\x06 \x01(\bR\n" +
	"libbpfCore\x12-\n" +
	"\x12bpftrace_available\x18\a \x01(\bR\x11bpftraceAvailable\x12)\n" +
	"\x10bpftrace_version\x18\b \x01(\tR\x0fbpftraceVersion\x12'\n" +
	"\x0fclang_available\x18\t \x01(\bR\x0eclangAvailable\x12#\n" +
	"\rclang_version\x18\n" +
	" \x01(\tR\fclangVersion\x12%\n" +
	"\x0ellvm_available\x18\v \x01(\bR\rllvmAvailable\x12!\n" +
	"\fllvm_version\x18\f \x01(\tR\vllvmVersion\x128\n" +
	"\x18kernel_headers_available\x18\r \x01(\bR\x16kernelHeadersAvailable\x12*\n" +
	"\x11go_ebpf_available\x18\x0e \x01(\bR\x0fgoEbpfAvailable\"[\n" +
	"\n" +
	"KernelInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x1f\n" +
	"\vbtf_enabled\x18\x03 \x01(\bR\n" +
	"btfEnabled\"\xcf\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vagent_token\x18\x02 \x01(\tR\n" +
	"agentToken\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12#\n" +
	"\ractive_probes\x18\x04 \x01(\x05R\factiveProbes\x12\x1f\n" +
	"\vcpu_percent\x18\x05 \x01(\x01R\n" +
	"cpuPercent\x12\x1b\n" +
	"\tmem_bytes\x18\x06 \x01(\x03R\bmemBytes\"a\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x122\n" +
	"\bcommands\x18\x02 \x03(\v2\x16.sentinel.ProbeCommandR\bcommands\"\x96\x02\n" +
	"\fProbeCommand\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".sentinel.ProbeCommand.CommandTypeR\x04type\x12\x19\n" +
	"\bprobe_id\x18\x02 \x01(\tR\aprobeId\x12\x1d\n" +
	"\n" +
	"probe_name\x18\x03 \x01(\tR\tprobeName\x12\x1d\n" +
	"\n" +
	"probe_data\x18\x04 \x01(\fR\tprobeData\x12\x1f\n" +
	"\vconfig_keys\x18\x05 \x03(\tR\n" +
	"configKeys\x12#\n" +
	"\rconfig_values\x18\x06 \x03(\tR\fconfigValues\"/\n" +
	"\vCommandType\x12\b\n" +
	"\x04LOAD\x10\x00\x12\n" +
	"\n" +
	"\x06UNLOAD\x10\x01\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x02\"\xdf\x01\n" +
	"\n" +
	"ProbeEvent\x12\x19\n" +
	"\bprobe_id\x18\x01 \x01(\tR\aprobeId\x12\x1d\n" +
	"\n" +
	"probe_name\x18\x02 \x01(\tR\tprobeName\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04comm\x18\x06 \x01(\tR\x04comm\x12\x1a\n" +
	"\bfilename\x18\a \x01(\tR\bfilename\x12\x18\n" +
	"\adetails\x18\b \x01(\tR\adetails\"w\n" +
	"\vEventReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vagent_token\x18\x02 \x01(\tR\n" +
	"agentToken\x12,\n" +
	"\x06events\x18\x03 \x03(\v2\x14.sentinel.ProbeEventR\x06events2\xdb\x01\n" +
	"\bSentinel\x12A\n" +
	"\bRegister\x12\x19.sentinel.RegisterRequest\x1a\x1a.sentinel.RegisterResponse\x12H\n" +
	"\tHeartbeat\x12\x1a.sentinel.HeartbeatRequest\x1a\x1b.sentinel.HeartbeatResponse(\x010\x01\x12B\n" +
	"\fReportEvents\x12\x15.sentinel.EventReport\x1a\x1b.sentinel.HeartbeatResponseB.Z,github.com/CoderXinNing/ebpf-system/proto/pbb\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_agent_proto_goTypes = []any{
	(ProbeCommand_CommandType)(0), // 0: sentinel.ProbeCommand.CommandType
	(*RegisterRequest)(nil),       // 1: sentinel.RegisterRequest
	(*RegisterResponse)(nil),      // 2: sentinel.RegisterResponse
	(*FrameworkInfo)(nil),         // 3: sentinel.FrameworkInfo
	(*KernelInfo)(nil),            // 4: sentinel.KernelInfo
	(*HeartbeatRequest)(nil),      // 5: sentinel.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 6: sentinel.HeartbeatResponse
	(*ProbeCommand)(nil),          // 7: sentinel.ProbeCommand
	(*ProbeEvent)(nil),            // 8: sentinel.ProbeEvent
	(*EventReport)(nil),           // 9: sentinel.EventReport
}
var file_proto_agent_proto_depIdxs = []int32{
	3, // 0: sentinel.RegisterRequest.framework:type_name -> sentinel.FrameworkInfo
	4, // 1: sentinel.RegisterRequest.kernel_info:type_name -> sentinel.KernelInfo
	7, // 2: sentinel.HeartbeatResponse.commands:type_name -> sentinel.ProbeCommand
	0, // 3: sentinel.ProbeCommand.type:type_name -> sentinel.ProbeCommand.CommandType
	8, // 4: sentinel.EventReport.events:type_name -> sentinel.ProbeEvent
	1, // 5: sentinel.Sentinel.Register:input_type -> sentinel.RegisterRequest
	5, // 6: sentinel.Sentinel.Heartbeat:input_type -> sentinel.HeartbeatRequest
	9, // 7: sentinel.Sentinel.ReportEvents:input_type -> sentinel.EventReport
	2, // 8: sentinel.Sentinel.Register:output_type -> sentinel.RegisterResponse
	6, // 9: sentinel.Sentinel.Heartbeat:output_type -> sentinel.HeartbeatResponse
	6, // 10: sentinel.Sentinel.ReportEvents:output_type -> sentinel.HeartbeatResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
