// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/agent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProbeCommand_CommandType int32

const (
	ProbeCommand_LOAD   ProbeCommand_CommandType = 0
	ProbeCommand_UNLOAD ProbeCommand_CommandType = 1
	ProbeCommand_UPDATE ProbeCommand_CommandType = 2
)

// Enum value maps for ProbeCommand_CommandType.
var (
	ProbeCommand_CommandType_name = map[int32]string{
		0: "LOAD",
		1: "UNLOAD",
		2: "UPDATE",
	}
	ProbeCommand_CommandType_value = map[string]int32{
		"LOAD":   0,
		"UNLOAD": 1,
		"UPDATE": 2,
	}
)

func (x ProbeCommand_CommandType) Enum() *ProbeCommand_CommandType {
	p := new(ProbeCommand_CommandType)
	*p = x
	return p
}

func (x ProbeCommand_CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProbeCommand_CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[0].Descriptor()
}

func (ProbeCommand_CommandType) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[0]
}

func (x ProbeCommand_CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProbeCommand_CommandType.Descriptor instead.
func (ProbeCommand_CommandType) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6, 0}
}

type ProbeStatus_Status int32

const (
	ProbeStatus_LOADED   ProbeStatus_Status = 0
	ProbeStatus_RUNNING  ProbeStatus_Status = 1
	ProbeStatus_ERROR    ProbeStatus_Status = 2
	ProbeStatus_UNLOADED ProbeStatus_Status = 3
)

// Enum value maps for ProbeStatus_Status.
var (
	ProbeStatus_Status_name = map[int32]string{
		0: "LOADED",
		1: "RUNNING",
		2: "ERROR",
		3: "UNLOADED",
	}
	ProbeStatus_Status_value = map[string]int32{
		"LOADED":   0,
		"RUNNING":  1,
		"ERROR":    2,
		"UNLOADED": 3,
	}
)

func (x ProbeStatus_Status) Enum() *ProbeStatus_Status {
	p := new(ProbeStatus_Status)
	*p = x
	return p
}

func (x ProbeStatus_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProbeStatus_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[1].Descriptor()
}

func (ProbeStatus_Status) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[1]
}

func (x ProbeStatus_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProbeStatus_Status.Descriptor instead.
func (ProbeStatus_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7, 0}
}

// 框架支持信息
type FrameworkInfo struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	BccAvailable           bool                   `protobuf:"varint,1,opt,name=bcc_available,json=bccAvailable,proto3" json:"bcc_available,omitempty"`
	BccVersion             string                 `protobuf:"bytes,2,opt,name=bcc_version,json=bccVersion,proto3" json:"bcc_version,omitempty"`
	PythonBccAvailable     bool                   `protobuf:"varint,3,opt,name=python_bcc_available,json=pythonBccAvailable,proto3" json:"python_bcc_available,omitempty"`
	LibbpfAvailable        bool                   `protobuf:"varint,4,opt,name=libbpf_available,json=libbpfAvailable,proto3" json:"libbpf_available,omitempty"`
	LibbpfVersion          string                 `protobuf:"bytes,5,opt,name=libbpf_version,json=libbpfVersion,proto3" json:"libbpf_version,omitempty"`
	LibbpfCore             bool                   `protobuf:"varint,6,opt,name=libbpf_core,json=libbpfCore,proto3" json:"libbpf_core,omitempty"`
	BpftraceAvailable      bool                   `protobuf:"varint,7,opt,name=bpftrace_available,json=bpftraceAvailable,proto3" json:"bpftrace_available,omitempty"`
	BpftraceVersion        string                 `protobuf:"bytes,8,opt,name=bpftrace_version,json=bpftraceVersion,proto3" json:"bpftrace_version,omitempty"`
	ClangAvailable         bool                   `protobuf:"varint,9,opt,name=clang_available,json=clangAvailable,proto3" json:"clang_available,omitempty"`
	ClangVersion           string                 `protobuf:"bytes,10,opt,name=clang_version,json=clangVersion,proto3" json:"clang_version,omitempty"`
	LlvmAvailable          bool                   `protobuf:"varint,11,opt,name=llvm_available,json=llvmAvailable,proto3" json:"llvm_available,omitempty"`
	LlvmVersion            string                 `protobuf:"bytes,12,opt,name=llvm_version,json=llvmVersion,proto3" json:"llvm_version,omitempty"`
	KernelHeadersAvailable bool                   `protobuf:"varint,13,opt,name=kernel_headers_available,json=kernelHeadersAvailable,proto3" json:"kernel_headers_available,omitempty"`
	GoEbpfAvailable        bool                   `protobuf:"varint,14,opt,name=go_ebpf_available,json=goEbpfAvailable,proto3" json:"go_ebpf_available,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FrameworkInfo) Reset() {
	*x = FrameworkInfo{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameworkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameworkInfo) ProtoMessage() {}

func (x *FrameworkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameworkInfo.ProtoReflect.Descriptor instead.
func (*FrameworkInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *FrameworkInfo) GetBccAvailable() bool {
	if x != nil {
		return x.BccAvailable
	}
	return false
}

func (x *FrameworkInfo) GetBccVersion() string {
	if x != nil {
		return x.BccVersion
	}
	return ""
}

func (x *FrameworkInfo) GetPythonBccAvailable() bool {
	if x != nil {
		return x.PythonBccAvailable
	}
	return false
}

func (x *FrameworkInfo) GetLibbpfAvailable() bool {
	if x != nil {
		return x.LibbpfAvailable
	}
	return false
}

func (x *FrameworkInfo) GetLibbpfVersion() string {
	if x != nil {
		return x.LibbpfVersion
	}
	return ""
}

func (x *FrameworkInfo) GetLibbpfCore() bool {
	if x != nil {
		return x.LibbpfCore
	}
	return false
}

func (x *FrameworkInfo) GetBpftraceAvailable() bool {
	if x != nil {
		return x.BpftraceAvailable
	}
	return false
}

func (x *FrameworkInfo) GetBpftraceVersion() string {
	if x != nil {
		return x.BpftraceVersion
	}
	return ""
}

func (x *FrameworkInfo) GetClangAvailable() bool {
	if x != nil {
		return x.ClangAvailable
	}
	return false
}

func (x *FrameworkInfo) GetClangVersion() string {
	if x != nil {
		return x.ClangVersion
	}
	return ""
}

func (x *FrameworkInfo) GetLlvmAvailable() bool {
	if x != nil {
		return x.LlvmAvailable
	}
	return false
}

func (x *FrameworkInfo) GetLlvmVersion() string {
	if x != nil {
		return x.LlvmVersion
	}
	return ""
}

func (x *FrameworkInfo) GetKernelHeadersAvailable() bool {
	if x != nil {
		return x.KernelHeadersAvailable
	}
	return false
}

func (x *FrameworkInfo) GetGoEbpfAvailable() bool {
	if x != nil {
		return x.GoEbpfAvailable
	}
	return false
}

// 内核特性信息
type KernelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	BtfEnabled    bool                   `protobuf:"varint,3,opt,name=btf_enabled,json=btfEnabled,proto3" json:"btf_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KernelInfo) Reset() {
	*x = KernelInfo{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelInfo) ProtoMessage() {}

func (x *KernelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelInfo.ProtoReflect.Descriptor instead.
func (*KernelInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *KernelInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *KernelInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *KernelInfo) GetBtfEnabled() bool {
	if x != nil {
		return x.BtfEnabled
	}
	return false
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	KernelVersion string                 `protobuf:"bytes,3,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	IpAddress     string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Framework     *FrameworkInfo         `protobuf:"bytes,5,opt,name=framework,proto3" json:"framework,omitempty"`
	KernelInfo    *KernelInfo            `protobuf:"bytes,6,opt,name=kernel_info,json=kernelInfo,proto3" json:"kernel_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *RegisterRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterRequest) GetFramework() *FrameworkInfo {
	if x != nil {
		return x.Framework
	}
	return nil
}

func (x *RegisterRequest) GetKernelInfo() *KernelInfo {
	if x != nil {
		return x.KernelInfo
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AgentToken    string                 `protobuf:"bytes,3,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentToken    string                 `protobuf:"bytes,2,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ActiveProbes  int32                  `protobuf:"varint,4,opt,name=active_probes,json=activeProbes,proto3" json:"active_probes,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,5,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemBytes      int64                  `protobuf:"varint,6,opt,name=mem_bytes,json=memBytes,proto3" json:"mem_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetActiveProbes() int32 {
	if x != nil {
		return x.ActiveProbes
	}
	return 0
}

func (x *HeartbeatRequest) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *HeartbeatRequest) GetMemBytes() int64 {
	if x != nil {
		return x.MemBytes
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Commands      []*ProbeCommand        `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetCommands() []*ProbeCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

type ProbeCommand struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Type          ProbeCommand_CommandType `protobuf:"varint,1,opt,name=type,proto3,enum=sentinel.ProbeCommand_CommandType" json:"type,omitempty"`
	ProbeId       string                   `protobuf:"bytes,2,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	ProbeName     string                   `protobuf:"bytes,3,opt,name=probe_name,json=probeName,proto3" json:"probe_name,omitempty"`
	ProbeData     []byte                   `protobuf:"bytes,4,opt,name=probe_data,json=probeData,proto3" json:"probe_data,omitempty"`
	ConfigKeys    []string                 `protobuf:"bytes,5,rep,name=config_keys,json=configKeys,proto3" json:"config_keys,omitempty"`
	ConfigValues  []string                 `protobuf:"bytes,6,rep,name=config_values,json=configValues,proto3" json:"config_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeCommand) Reset() {
	*x = ProbeCommand{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeCommand) ProtoMessage() {}

func (x *ProbeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeCommand.ProtoReflect.Descriptor instead.
func (*ProbeCommand) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ProbeCommand) GetType() ProbeCommand_CommandType {
	if x != nil {
		return x.Type
	}
	return ProbeCommand_LOAD
}

func (x *ProbeCommand) GetProbeId() string {
	if x != nil {
		return x.ProbeId
	}
	return ""
}

func (x *ProbeCommand) GetProbeName() string {
	if x != nil {
		return x.ProbeName
	}
	return ""
}

func (x *ProbeCommand) GetProbeData() []byte {
	if x != nil {
		return x.ProbeData
	}
	return nil
}

func (x *ProbeCommand) GetConfigKeys() []string {
	if x != nil {
		return x.ConfigKeys
	}
	return nil
}

func (x *ProbeCommand) GetConfigValues() []string {
	if x != nil {
		return x.ConfigValues
	}
	return nil
}

type ProbeStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProbeId         string                 `protobuf:"bytes,1,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	ProbeName       string                 `protobuf:"bytes,2,opt,name=probe_name,json=probeName,proto3" json:"probe_name,omitempty"`
	Status          ProbeStatus_Status     `protobuf:"varint,3,opt,name=status,proto3,enum=sentinel.ProbeStatus_Status" json:"status,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	EventsCollected int64                  `protobuf:"varint,5,opt,name=events_collected,json=eventsCollected,proto3" json:"events_collected,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProbeStatus) Reset() {
	*x = ProbeStatus{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeStatus) ProtoMessage() {}

func (x *ProbeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeStatus.ProtoReflect.Descriptor instead.
func (*ProbeStatus) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ProbeStatus) GetProbeId() string {
	if x != nil {
		return x.ProbeId
	}
	return ""
}

func (x *ProbeStatus) GetProbeName() string {
	if x != nil {
		return x.ProbeName
	}
	return ""
}

func (x *ProbeStatus) GetStatus() ProbeStatus_Status {
	if x != nil {
		return x.Status
	}
	return ProbeStatus_LOADED
}

func (x *ProbeStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ProbeStatus) GetEventsCollected() int64 {
	if x != nil {
		return x.EventsCollected
	}
	return 0
}

type AlertEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AlertId        string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	ProbeId        string                 `protobuf:"bytes,2,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	ProbeName      string                 `protobuf:"bytes,3,opt,name=probe_name,json=probeName,proto3" json:"probe_name,omitempty"`
	Severity       string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	Title          string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Timestamp      int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Pid            int32                  `protobuf:"varint,8,opt,name=pid,proto3" json:"pid,omitempty"`
	ProcessName    string                 `protobuf:"bytes,9,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	MetadataKeys   []string               `protobuf:"bytes,10,rep,name=metadata_keys,json=metadataKeys,proto3" json:"metadata_keys,omitempty"`
	MetadataValues []string               `protobuf:"bytes,11,rep,name=metadata_values,json=metadataValues,proto3" json:"metadata_values,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AlertEvent) Reset() {
	*x = AlertEvent{}
	mi := &file_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertEvent) ProtoMessage() {}

func (x *AlertEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertEvent.ProtoReflect.Descriptor instead.
func (*AlertEvent) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *AlertEvent) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *AlertEvent) GetProbeId() string {
	if x != nil {
		return x.ProbeId
	}
	return ""
}

func (x *AlertEvent) GetProbeName() string {
	if x != nil {
		return x.ProbeName
	}
	return ""
}

func (x *AlertEvent) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *AlertEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AlertEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AlertEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AlertEvent) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *AlertEvent) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *AlertEvent) GetMetadataKeys() []string {
	if x != nil {
		return x.MetadataKeys
	}
	return nil
}

func (x *AlertEvent) GetMetadataValues() []string {
	if x != nil {
		return x.MetadataValues
	}
	return nil
}

type AgentReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentToken    string                 `protobuf:"bytes,2,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	ProbeStatuses []*ProbeStatus         `protobuf:"bytes,3,rep,name=probe_statuses,json=probeStatuses,proto3" json:"probe_statuses,omitempty"`
	Alerts        []*AlertEvent          `protobuf:"bytes,4,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentReport) Reset() {
	*x = AgentReport{}
	mi := &file_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentReport) ProtoMessage() {}

func (x *AgentReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentReport.ProtoReflect.Descriptor instead.
func (*AgentReport) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *AgentReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentReport) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

func (x *AgentReport) GetProbeStatuses() []*ProbeStatus {
	if x != nil {
		return x.ProbeStatuses
	}
	return nil
}

func (x *AgentReport) GetAlerts() []*AlertEvent {
	if x != nil {
		return x.Alerts
	}
	return nil
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\bsentinel\"\xd2\x04\n" +
	"\rFrameworkInfo\x12#\n" +
	"\rbcc_available\x18\x01 \x01(\bR\fbccAvailable\x12\x1f\n" +
	"\vbcc_version\x18\x02 \x01(\tR\n" +
	"bccVersion\x120\n" +
	"\x14python_bcc_available\x18\x03 \x01(\bR\x12pythonBccAvailable\x12)\n" +
	"\x10libbpf_available\x18\x04 \x01(\bR\x0flibbpfAvailable\x12%\n" +
	"\x0elibbpf_version\x18\x05 \x01(\tR\rlibbpfVersion\x12\x1f\n" +
	"\vlibbpf_core\x18\x06 \x01(\bR\n" +
	"libbpfCore\x12-\n" +
	"\x12bpftrace_available\x18\a \x01(\bR\x11bpftraceAvailable\x12)\n" +
	"\x10bpftrace_version\x18\b \x01(\tR\x0fbpftraceVersion\x12'\n" +
	"\x0fclang_available\x18\t \x01(\bR\x0eclangAvailable\x12#\n" +
	"\rclang_version\x18\n" +
	" \x01(\tR\fclangVersion\x12%\n" +
	"\x0ellvm_available\x18\v \x01(\bR\rllvmAvailable\x12!\n" +
	"\fllvm_version\x18\f \x01(\tR\vllvmVersion\x128\n" +
	"\x18kernel_headers_available\x18\r \x01(\bR\x16kernelHeadersAvailable\x12*\n" +
	"\x11go_ebpf_available\x18\x0e \x01(\bR\x0fgoEbpfAvailable\"[\n" +
	"\n" +
	"KernelInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x1f\n" +
	"\vbtf_enabled\x18\x03 \x01(\bR\n" +
	"btfEnabled\"\xfc\x01\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12%\n" +
	"\x0ekernel_version\x18\x03 \x01(\tR\rkernelVersion\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x125\n" +
	"\tframework\x18\x05 \x01(\v2\x17.sentinel.FrameworkInfoR\tframework\x125\n" +
	"\vkernel_info\x18\x06 \x01(\v2\x14.sentinel.KernelInfoR\n" +
	"kernelInfo\"g\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vagent_token\x18\x03 \x01(\tR\n" +
	"agentToken\"\xcf\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vagent_token\x18\x02 \x01(\tR\n" +
	"agentToken\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12#\n" +
	"\ractive_probes\x18\x04 \x01(\x05R\factiveProbes\x12\x1f\n" +
	"\vcpu_percent\x18\x05 \x01(\x01R\n" +
	"cpuPercent\x12\x1b\n" +
	"\tmem_bytes\x18\x06 \x01(\x03R\bmemBytes\"a\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x122\n" +
	"\bcommands\x18\x02 \x03(\v2\x16.sentinel.ProbeCommandR\bcommands\"\x96\x02\n" +
	"\fProbeCommand\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".sentinel.ProbeCommand.CommandTypeR\x04type\x12\x19\n" +
	"\bprobe_id\x18\x02 \x01(\tR\aprobeId\x12\x1d\n" +
	"\n" +
	"probe_name\x18\x03 \x01(\tR\tprobeName\x12\x1d\n" +
	"\n" +
	"probe_data\x18\x04 \x01(\fR\tprobeData\x12\x1f\n" +
	"\vconfig_keys\x18\x05 \x03(\tR\n" +
	"configKeys\x12#\n" +
	"\rconfig_values\x18\x06 \x03(\tR\fconfigValues\"/\n" +
	"\vCommandType\x12\b\n" +
	"\x04LOAD\x10\x00\x12\n" +
	"\n" +
	"\x06UNLOAD\x10\x01\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x02\"\x89\x02\n" +
	"\vProbeStatus\x12\x19\n" +
	"\bprobe_id\x18\x01 \x01(\tR\aprobeId\x12\x1d\n" +
	"\n" +
	"probe_name\x18\x02 \x01(\tR\tprobeName\x124\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1c.sentinel.ProbeStatus.StatusR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12)\n" +
	"\x10events_collected\x18\x05 \x01(\x03R\x0feventsCollected\":\n" +
	"\x06Status\x12\n" +
	"\n" +
	"\x06LOADED\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02\x12\f\n" +
	"\bUNLOADED\x10\x03\"\xd6\x02\n" +
	"\n" +
	"AlertEvent\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\x12\x19\n" +
	"\bprobe_id\x18\x02 \x01(\tR\aprobeId\x12\x1d\n" +
	"\n" +
	"probe_name\x18\x03 \x01(\tR\tprobeName\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x10\n" +
	"\x03pid\x18\b \x01(\x05R\x03pid\x12!\n" +
	"\fprocess_name\x18\t \x01(\tR\vprocessName\x12#\n" +
	"\rmetadata_keys\x18\n" +
	" \x03(\tR\fmetadataKeys\x12'\n" +
	"\x0fmetadata_values\x18\v \x03(\tR\x0emetadataValues\"\xb5\x01\n" +
	"\vAgentReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vagent_token\x18\x02 \x01(\tR\n" +
	"agentToken\x12<\n" +
	"\x0eprobe_statuses\x18\x03 \x03(\v2\x15.sentinel.ProbeStatusR\rprobeStatuses\x12,\n" +
	"\x06alerts\x18\x04 \x03(\v2\x14.sentinel.AlertEventR\x06alerts2\xd5\x01\n" +
	"\bSentinel\x12A\n" +
	"\bRegister\x12\x19.sentinel.RegisterRequest\x1a\x1a.sentinel.RegisterResponse\x12H\n" +
	"\tHeartbeat\x12\x1a.sentinel.HeartbeatRequest\x1a\x1b.sentinel.HeartbeatResponse(\x010\x01\x12<\n" +
	"\x06Report\x12\x15.sentinel.AgentReport\x1a\x1b.sentinel.HeartbeatResponseB.Z,github.com/CoderXinNing/ebpf-system/proto/pbb\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_agent_proto_goTypes = []any{
	(ProbeCommand_CommandType)(0), // 0: sentinel.ProbeCommand.CommandType
	(ProbeStatus_Status)(0),       // 1: sentinel.ProbeStatus.Status
	(*FrameworkInfo)(nil),         // 2: sentinel.FrameworkInfo
	(*KernelInfo)(nil),            // 3: sentinel.KernelInfo
	(*RegisterRequest)(nil),       // 4: sentinel.RegisterRequest
	(*RegisterResponse)(nil),      // 5: sentinel.RegisterResponse
	(*HeartbeatRequest)(nil),      // 6: sentinel.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 7: sentinel.HeartbeatResponse
	(*ProbeCommand)(nil),          // 8: sentinel.ProbeCommand
	(*ProbeStatus)(nil),           // 9: sentinel.ProbeStatus
	(*AlertEvent)(nil),            // 10: sentinel.AlertEvent
	(*AgentReport)(nil),           // 11: sentinel.AgentReport
}
var file_proto_agent_proto_depIdxs = []int32{
	2,  // 0: sentinel.RegisterRequest.framework:type_name -> sentinel.FrameworkInfo
	3,  // 1: sentinel.RegisterRequest.kernel_info:type_name -> sentinel.KernelInfo
	8,  // 2: sentinel.HeartbeatResponse.commands:type_name -> sentinel.ProbeCommand
	0,  // 3: sentinel.ProbeCommand.type:type_name -> sentinel.ProbeCommand.CommandType
	1,  // 4: sentinel.ProbeStatus.status:type_name -> sentinel.ProbeStatus.Status
	9,  // 5: sentinel.AgentReport.probe_statuses:type_name -> sentinel.ProbeStatus
	10, // 6: sentinel.AgentReport.alerts:type_name -> sentinel.AlertEvent
	4,  // 7: sentinel.Sentinel.Register:input_type -> sentinel.RegisterRequest
	6,  // 8: sentinel.Sentinel.Heartbeat:input_type -> sentinel.HeartbeatRequest
	11, // 9: sentinel.Sentinel.Report:input_type -> sentinel.AgentReport
	5,  // 10: sentinel.Sentinel.Register:output_type -> sentinel.RegisterResponse
	7,  // 11: sentinel.Sentinel.Heartbeat:output_type -> sentinel.HeartbeatResponse
	7,  // 12: sentinel.Sentinel.Report:output_type -> sentinel.HeartbeatResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
