// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.12.4
// source: agent_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterRequest 注册请求（token 由服务端生成返回）
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	KernelVersion string                 `protobuf:"bytes,3,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	IpAddress     string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,5,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	AgentGroup    string                 `protobuf:"bytes,6,opt,name=agent_group,json=agentGroup,proto3" json:"agent_group,omitempty"`
	Framework     *FrameworkInfo         `protobuf:"bytes,7,opt,name=framework,proto3" json:"framework,omitempty"`
	KernelInfo    *KernelInfo            `protobuf:"bytes,8,opt,name=kernel_info,json=kernelInfo,proto3" json:"kernel_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_agent_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *RegisterRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterRequest) GetAgentGroup() string {
	if x != nil {
		return x.AgentGroup
	}
	return ""
}

func (x *RegisterRequest) GetFramework() *FrameworkInfo {
	if x != nil {
		return x.Framework
	}
	return nil
}

func (x *RegisterRequest) GetKernelInfo() *KernelInfo {
	if x != nil {
		return x.KernelInfo
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AgentToken    string                 `protobuf:"bytes,3,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"` // 仅在注册响应中返回，后续通过 Metadata 传递
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_agent_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

type FrameworkInfo struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	BccAvailable           bool                   `protobuf:"varint,1,opt,name=bcc_available,json=bccAvailable,proto3" json:"bcc_available,omitempty"`
	LibbpfAvailable        bool                   `protobuf:"varint,2,opt,name=libbpf_available,json=libbpfAvailable,proto3" json:"libbpf_available,omitempty"`
	LibbpfCore             bool                   `protobuf:"varint,3,opt,name=libbpf_core,json=libbpfCore,proto3" json:"libbpf_core,omitempty"`
	BpftraceAvailable      bool                   `protobuf:"varint,4,opt,name=bpftrace_available,json=bpftraceAvailable,proto3" json:"bpftrace_available,omitempty"`
	ClangAvailable         bool                   `protobuf:"varint,5,opt,name=clang_available,json=clangAvailable,proto3" json:"clang_available,omitempty"`
	LlvmAvailable          bool                   `protobuf:"varint,6,opt,name=llvm_available,json=llvmAvailable,proto3" json:"llvm_available,omitempty"`
	KernelHeadersAvailable bool                   `protobuf:"varint,7,opt,name=kernel_headers_available,json=kernelHeadersAvailable,proto3" json:"kernel_headers_available,omitempty"`
	GoEbpfAvailable        bool                   `protobuf:"varint,8,opt,name=go_ebpf_available,json=goEbpfAvailable,proto3" json:"go_ebpf_available,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FrameworkInfo) Reset() {
	*x = FrameworkInfo{}
	mi := &file_agent_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameworkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameworkInfo) ProtoMessage() {}

func (x *FrameworkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameworkInfo.ProtoReflect.Descriptor instead.
func (*FrameworkInfo) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{2}
}

func (x *FrameworkInfo) GetBccAvailable() bool {
	if x != nil {
		return x.BccAvailable
	}
	return false
}

func (x *FrameworkInfo) GetLibbpfAvailable() bool {
	if x != nil {
		return x.LibbpfAvailable
	}
	return false
}

func (x *FrameworkInfo) GetLibbpfCore() bool {
	if x != nil {
		return x.LibbpfCore
	}
	return false
}

func (x *FrameworkInfo) GetBpftraceAvailable() bool {
	if x != nil {
		return x.BpftraceAvailable
	}
	return false
}

func (x *FrameworkInfo) GetClangAvailable() bool {
	if x != nil {
		return x.ClangAvailable
	}
	return false
}

func (x *FrameworkInfo) GetLlvmAvailable() bool {
	if x != nil {
		return x.LlvmAvailable
	}
	return false
}

func (x *FrameworkInfo) GetKernelHeadersAvailable() bool {
	if x != nil {
		return x.KernelHeadersAvailable
	}
	return false
}

func (x *FrameworkInfo) GetGoEbpfAvailable() bool {
	if x != nil {
		return x.GoEbpfAvailable
	}
	return false
}

type KernelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	BtfEnabled    bool                   `protobuf:"varint,3,opt,name=btf_enabled,json=btfEnabled,proto3" json:"btf_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KernelInfo) Reset() {
	*x = KernelInfo{}
	mi := &file_agent_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelInfo) ProtoMessage() {}

func (x *KernelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelInfo.ProtoReflect.Descriptor instead.
func (*KernelInfo) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{3}
}

func (x *KernelInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *KernelInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *KernelInfo) GetBtfEnabled() bool {
	if x != nil {
		return x.BtfEnabled
	}
	return false
}

// HeartbeatRequest 心跳（Unary RPC）
type HeartbeatRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AgentId           string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp         int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ActiveProbes      int32                  `protobuf:"varint,3,opt,name=active_probes,json=activeProbes,proto3" json:"active_probes,omitempty"`
	ProbeDetails      string                 `protobuf:"bytes,4,opt,name=probe_details,json=probeDetails,proto3" json:"probe_details,omitempty"`
	BaselineState     string                 `protobuf:"bytes,5,opt,name=baseline_state,json=baselineState,proto3" json:"baseline_state,omitempty"`
	BaselineRemaining int64                  `protobuf:"varint,6,opt,name=baseline_remaining,json=baselineRemaining,proto3" json:"baseline_remaining,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetActiveProbes() int32 {
	if x != nil {
		return x.ActiveProbes
	}
	return 0
}

func (x *HeartbeatRequest) GetProbeDetails() string {
	if x != nil {
		return x.ProbeDetails
	}
	return ""
}

func (x *HeartbeatRequest) GetBaselineState() string {
	if x != nil {
		return x.BaselineState
	}
	return ""
}

func (x *HeartbeatRequest) GetBaselineRemaining() int64 {
	if x != nil {
		return x.BaselineRemaining
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Commands      []*ProbeCommand        `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetCommands() []*ProbeCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

// ProbeEvent 探针事件
type ProbeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProbeId       string                 `protobuf:"bytes,1,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	ProbeName     string                 `protobuf:"bytes,2,opt,name=probe_name,json=probeName,proto3" json:"probe_name,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Pid           int32                  `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`
	Comm          string                 `protobuf:"bytes,6,opt,name=comm,proto3" json:"comm,omitempty"`
	Filename      string                 `protobuf:"bytes,7,opt,name=filename,proto3" json:"filename,omitempty"`
	Details       string                 `protobuf:"bytes,8,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeEvent) Reset() {
	*x = ProbeEvent{}
	mi := &file_agent_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeEvent) ProtoMessage() {}

func (x *ProbeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeEvent.ProtoReflect.Descriptor instead.
func (*ProbeEvent) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{6}
}

func (x *ProbeEvent) GetProbeId() string {
	if x != nil {
		return x.ProbeId
	}
	return ""
}

func (x *ProbeEvent) GetProbeName() string {
	if x != nil {
		return x.ProbeName
	}
	return ""
}

func (x *ProbeEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ProbeEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ProbeEvent) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProbeEvent) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *ProbeEvent) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ProbeEvent) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

// EventReport 事件上报
type EventReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Events        []*ProbeEvent          `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventReport) Reset() {
	*x = EventReport{}
	mi := &file_agent_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventReport) ProtoMessage() {}

func (x *EventReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventReport.ProtoReflect.Descriptor instead.
func (*EventReport) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{7}
}

func (x *EventReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EventReport) GetEvents() []*ProbeEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// ShutdownRequest 下线通知
type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_agent_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{8}
}

func (x *ShutdownRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_agent_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{9}
}

func (x *ShutdownResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ProbeListRequest 探针名单查询
type ProbeListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeListRequest) Reset() {
	*x = ProbeListRequest{}
	mi := &file_agent_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeListRequest) ProtoMessage() {}

func (x *ProbeListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeListRequest.ProtoReflect.Descriptor instead.
func (*ProbeListRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{10}
}

func (x *ProbeListRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type ProbeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Remove        bool                   `protobuf:"varint,3,opt,name=remove,proto3" json:"remove,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Sha256        string                 `protobuf:"bytes,5,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeInfo) Reset() {
	*x = ProbeInfo{}
	mi := &file_agent_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeInfo) ProtoMessage() {}

func (x *ProbeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeInfo.ProtoReflect.Descriptor instead.
func (*ProbeInfo) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{11}
}

func (x *ProbeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProbeInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ProbeInfo) GetRemove() bool {
	if x != nil {
		return x.Remove
	}
	return false
}

func (x *ProbeInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ProbeInfo) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type ProbeListResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Success               bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message               string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Probes                []*ProbeInfo           `protobuf:"bytes,3,rep,name=probes,proto3" json:"probes,omitempty"`
	FalsePositiveFeatures []string               `protobuf:"bytes,4,rep,name=false_positive_features,json=falsePositiveFeatures,proto3" json:"false_positive_features,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ProbeListResponse) Reset() {
	*x = ProbeListResponse{}
	mi := &file_agent_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeListResponse) ProtoMessage() {}

func (x *ProbeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeListResponse.ProtoReflect.Descriptor instead.
func (*ProbeListResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{12}
}

func (x *ProbeListResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProbeListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProbeListResponse) GetProbes() []*ProbeInfo {
	if x != nil {
		return x.Probes
	}
	return nil
}

func (x *ProbeListResponse) GetFalsePositiveFeatures() []string {
	if x != nil {
		return x.FalsePositiveFeatures
	}
	return nil
}

var File_agent_service_proto protoreflect.FileDescriptor

const file_agent_service_proto_rawDesc = "" +
	"\n" +
	"\x13agent_service.proto\x12\bsentinel\x1a\fcommon.proto\x1a\vasset.proto\"\xc2\x02\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12%\n" +
	"\x0ekernel_version\x18\x03 \x01(\tR\rkernelVersion\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12#\n" +
	"\ragent_version\x18\x05 \x01(\tR\fagentVersion\x12\x1f\n" +
	"\vagent_group\x18\x06 \x01(\tR\n" +
	"agentGroup\x125\n" +
	"\tframework\x18\a \x01(\v2\x17.sentinel.FrameworkInfoR\tframework\x125\n" +
	"\vkernel_info\x18\b \x01(\v2\x14.sentinel.KernelInfoR\n" +
	"kernelInfo\"g\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vagent_token\x18\x03 \x01(\tR\n" +
	"agentToken\"\xe5\x02\n" +
	"\rFrameworkInfo\x12#\n" +
	"\rbcc_available\x18\x01 \x01(\bR\fbccAvailable\x12)\n" +
	"\x10libbpf_available\x18\x02 \x01(\bR\x0flibbpfAvailable\x12\x1f\n" +
	"\vlibbpf_core\x18\x03 \x01(\bR\n" +
	"libbpfCore\x12-\n" +
	"\x12bpftrace_available\x18\x04 \x01(\bR\x11bpftraceAvailable\x12'\n" +
	"\x0fclang_available\x18\x05 \x01(\bR\x0eclangAvailable\x12%\n" +
	"\x0ellvm_available\x18\x06 \x01(\bR\rllvmAvailable\x128\n" +
	"\x18kernel_headers_available\x18\a \x01(\bR\x16kernelHeadersAvailable\x12*\n" +
	"\x11go_ebpf_available\x18\b \x01(\bR\x0fgoEbpfAvailable\"[\n" +
	"\n" +
	"KernelInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x1f\n" +
	"\vbtf_enabled\x18\x03 \x01(\bR\n" +
	"btfEnabled\"\xeb\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12#\n" +
	"\ractive_probes\x18\x03 \x01(\x05R\factiveProbes\x12#\n" +
	"\rprobe_details\x18\x04 \x01(\tR\fprobeDetails\x12%\n" +
	"\x0ebaseline_state\x18\x05 \x01(\tR\rbaselineState\x12-\n" +
	"\x12baseline_remaining\x18\x06 \x01(\x03R\x11baselineRemaining\"a\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x122\n" +
	"\bcommands\x18\x02 \x03(\v2\x16.sentinel.ProbeCommandR\bcommands\"\xdf\x01\n" +
	"\n" +
	"ProbeEvent\x12\x19\n" +
	"\bprobe_id\x18\x01 \x01(\tR\aprobeId\x12\x1d\n" +
	"\n" +
	"probe_name\x18\x02 \x01(\tR\tprobeName\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04comm\x18\x06 \x01(\tR\x04comm\x12\x1a\n" +
	"\bfilename\x18\a \x01(\tR\bfilename\x12\x18\n" +
	"\adetails\x18\b \x01(\tR\adetails\"V\n" +
	"\vEventReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12,\n" +
	"\x06events\x18\x02 \x03(\v2\x14.sentinel.ProbeEventR\x06events\",\n" +
	"\x0fShutdownRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\",\n" +
	"\x10ShutdownResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"-\n" +
	"\x10ProbeListRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"}\n" +
	"\tProbeInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12\x16\n" +
	"\x06remove\x18\x03 \x01(\bR\x06remove\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x16\n" +
	"\x06sha256\x18\x05 \x01(\tR\x06sha256\"\xac\x01\n" +
	"\x11ProbeListResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x06probes\x18\x03 \x03(\v2\x13.sentinel.ProbeInfoR\x06probes\x126\n" +
	"\x17false_positive_features\x18\x04 \x03(\tR\x15falsePositiveFeatures2\xe3\b\n" +
	"\bSentinel\x12A\n" +
	"\bRegister\x12\x19.sentinel.RegisterRequest\x1a\x1a.sentinel.RegisterResponse\x12D\n" +
	"\tHeartbeat\x12\x1a.sentinel.HeartbeatRequest\x1a\x1b.sentinel.HeartbeatResponse\x12?\n" +
	"\fReportEvents\x12\x15.sentinel.EventReport\x1a\x18.sentinel.ReportResponse\x12G\n" +
	"\fGetProbeList\x12\x1a.sentinel.ProbeListRequest\x1a\x1b.sentinel.ProbeListResponse\x12G\n" +
	"\x0eReportShutdown\x12\x19.sentinel.ShutdownRequest\x1a\x1a.sentinel.ShutdownResponse\x12D\n" +
	"\x0fReportProcesses\x12\x17.sentinel.ProcessReport\x1a\x18.sentinel.ReportResponse\x12=\n" +
	"\vReportUsers\x12\x14.sentinel.UserReport\x1a\x18.sentinel.ReportResponse\x12D\n" +
	"\x10ReportSystemInfo\x12\x16.sentinel.SystemReport\x1a\x18.sentinel.ReportResponse\x12C\n" +
	"\x0eReportPackages\x12\x17.sentinel.PackageReport\x1a\x18.sentinel.ReportResponse\x12@\n" +
	"\x0eReportCronJobs\x12\x14.sentinel.CronReport\x1a\x18.sentinel.ReportResponse\x12C\n" +
	"\x0eReportServices\x12\x17.sentinel.ServiceReport\x1a\x18.sentinel.ReportResponse\x12M\n" +
	"\x13ReportWebComponents\x12\x1c.sentinel.WebComponentReport\x1a\x18.sentinel.ReportResponse\x12D\n" +
	"\x0eReportHardware\x12\x18.sentinel.HardwareReport\x1a\x18.sentinel.ReportResponse\x12B\n" +
	"\rReportNetwork\x12\x17.sentinel.NetworkReport\x1a\x18.sentinel.ReportResponse\x12C\n" +
	"\x11ReportPerformance\x12\x14.sentinel.PerfReport\x1a\x18.sentinel.ReportResponse\x12F\n" +
	"\x0fReportAgentSelf\x12\x19.sentinel.AgentSelfReport\x1a\x18.sentinel.ReportResponseB.Z,github.com/CoderXinNing/ebpf-system/proto/pbb\x06proto3"

var (
	file_agent_service_proto_rawDescOnce sync.Once
	file_agent_service_proto_rawDescData []byte
)

func file_agent_service_proto_rawDescGZIP() []byte {
	file_agent_service_proto_rawDescOnce.Do(func() {
		file_agent_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_service_proto_rawDesc), len(file_agent_service_proto_rawDesc)))
	})
	return file_agent_service_proto_rawDescData
}

var file_agent_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_agent_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),    // 0: sentinel.RegisterRequest
	(*RegisterResponse)(nil),   // 1: sentinel.RegisterResponse
	(*FrameworkInfo)(nil),      // 2: sentinel.FrameworkInfo
	(*KernelInfo)(nil),         // 3: sentinel.KernelInfo
	(*HeartbeatRequest)(nil),   // 4: sentinel.HeartbeatRequest
	(*HeartbeatResponse)(nil),  // 5: sentinel.HeartbeatResponse
	(*ProbeEvent)(nil),         // 6: sentinel.ProbeEvent
	(*EventReport)(nil),        // 7: sentinel.EventReport
	(*ShutdownRequest)(nil),    // 8: sentinel.ShutdownRequest
	(*ShutdownResponse)(nil),   // 9: sentinel.ShutdownResponse
	(*ProbeListRequest)(nil),   // 10: sentinel.ProbeListRequest
	(*ProbeInfo)(nil),          // 11: sentinel.ProbeInfo
	(*ProbeListResponse)(nil),  // 12: sentinel.ProbeListResponse
	(*ProbeCommand)(nil),       // 13: sentinel.ProbeCommand
	(*ProcessReport)(nil),      // 14: sentinel.ProcessReport
	(*UserReport)(nil),         // 15: sentinel.UserReport
	(*SystemReport)(nil),       // 16: sentinel.SystemReport
	(*PackageReport)(nil),      // 17: sentinel.PackageReport
	(*CronReport)(nil),         // 18: sentinel.CronReport
	(*ServiceReport)(nil),      // 19: sentinel.ServiceReport
	(*WebComponentReport)(nil), // 20: sentinel.WebComponentReport
	(*HardwareReport)(nil),     // 21: sentinel.HardwareReport
	(*NetworkReport)(nil),      // 22: sentinel.NetworkReport
	(*PerfReport)(nil),         // 23: sentinel.PerfReport
	(*AgentSelfReport)(nil),    // 24: sentinel.AgentSelfReport
	(*ReportResponse)(nil),     // 25: sentinel.ReportResponse
}
var file_agent_service_proto_depIdxs = []int32{
	2,  // 0: sentinel.RegisterRequest.framework:type_name -> sentinel.FrameworkInfo
	3,  // 1: sentinel.RegisterRequest.kernel_info:type_name -> sentinel.KernelInfo
	13, // 2: sentinel.HeartbeatResponse.commands:type_name -> sentinel.ProbeCommand
	6,  // 3: sentinel.EventReport.events:type_name -> sentinel.ProbeEvent
	11, // 4: sentinel.ProbeListResponse.probes:type_name -> sentinel.ProbeInfo
	0,  // 5: sentinel.Sentinel.Register:input_type -> sentinel.RegisterRequest
	4,  // 6: sentinel.Sentinel.Heartbeat:input_type -> sentinel.HeartbeatRequest
	7,  // 7: sentinel.Sentinel.ReportEvents:input_type -> sentinel.EventReport
	10, // 8: sentinel.Sentinel.GetProbeList:input_type -> sentinel.ProbeListRequest
	8,  // 9: sentinel.Sentinel.ReportShutdown:input_type -> sentinel.ShutdownRequest
	14, // 10: sentinel.Sentinel.ReportProcesses:input_type -> sentinel.ProcessReport
	15, // 11: sentinel.Sentinel.ReportUsers:input_type -> sentinel.UserReport
	16, // 12: sentinel.Sentinel.ReportSystemInfo:input_type -> sentinel.SystemReport
	17, // 13: sentinel.Sentinel.ReportPackages:input_type -> sentinel.PackageReport
	18, // 14: sentinel.Sentinel.ReportCronJobs:input_type -> sentinel.CronReport
	19, // 15: sentinel.Sentinel.ReportServices:input_type -> sentinel.ServiceReport
	20, // 16: sentinel.Sentinel.ReportWebComponents:input_type -> sentinel.WebComponentReport
	21, // 17: sentinel.Sentinel.ReportHardware:input_type -> sentinel.HardwareReport
	22, // 18: sentinel.Sentinel.ReportNetwork:input_type -> sentinel.NetworkReport
	23, // 19: sentinel.Sentinel.ReportPerformance:input_type -> sentinel.PerfReport
	24, // 20: sentinel.Sentinel.ReportAgentSelf:input_type -> sentinel.AgentSelfReport
	1,  // 21: sentinel.Sentinel.Register:output_type -> sentinel.RegisterResponse
	5,  // 22: sentinel.Sentinel.Heartbeat:output_type -> sentinel.HeartbeatResponse
	25, // 23: sentinel.Sentinel.ReportEvents:output_type -> sentinel.ReportResponse
	12, // 24: sentinel.Sentinel.GetProbeList:output_type -> sentinel.ProbeListResponse
	9,  // 25: sentinel.Sentinel.ReportShutdown:output_type -> sentinel.ShutdownResponse
	25, // 26: sentinel.Sentinel.ReportProcesses:output_type -> sentinel.ReportResponse
	25, // 27: sentinel.Sentinel.ReportUsers:output_type -> sentinel.ReportResponse
	25, // 28: sentinel.Sentinel.ReportSystemInfo:output_type -> sentinel.ReportResponse
	25, // 29: sentinel.Sentinel.ReportPackages:output_type -> sentinel.ReportResponse
	25, // 30: sentinel.Sentinel.ReportCronJobs:output_type -> sentinel.ReportResponse
	25, // 31: sentinel.Sentinel.ReportServices:output_type -> sentinel.ReportResponse
	25, // 32: sentinel.Sentinel.ReportWebComponents:output_type -> sentinel.ReportResponse
	25, // 33: sentinel.Sentinel.ReportHardware:output_type -> sentinel.ReportResponse
	25, // 34: sentinel.Sentinel.ReportNetwork:output_type -> sentinel.ReportResponse
	25, // 35: sentinel.Sentinel.ReportPerformance:output_type -> sentinel.ReportResponse
	25, // 36: sentinel.Sentinel.ReportAgentSelf:output_type -> sentinel.ReportResponse
	21, // [21:37] is the sub-list for method output_type
	5,  // [5:21] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_agent_service_proto_init() }
func file_agent_service_proto_init() {
	if File_agent_service_proto != nil {
		return
	}
	file_common_proto_init()
	file_asset_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_service_proto_rawDesc), len(file_agent_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_service_proto_goTypes,
		DependencyIndexes: file_agent_service_proto_depIdxs,
		MessageInfos:      file_agent_service_proto_msgTypes,
	}.Build()
	File_agent_service_proto = out.File
	file_agent_service_proto_goTypes = nil
	file_agent_service_proto_depIdxs = nil
}
