// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/agent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProbeCommand_CommandType int32

const (
	ProbeCommand_LOAD      ProbeCommand_CommandType = 0
	ProbeCommand_UNLOAD    ProbeCommand_CommandType = 1
	ProbeCommand_RELOAD    ProbeCommand_CommandType = 3
	ProbeCommand_INSTALL   ProbeCommand_CommandType = 4
	ProbeCommand_COLLECT   ProbeCommand_CommandType = 5
	ProbeCommand_SET_GROUP ProbeCommand_CommandType = 6
)

// Enum value maps for ProbeCommand_CommandType.
var (
	ProbeCommand_CommandType_name = map[int32]string{
		0: "LOAD",
		1: "UNLOAD",
		3: "RELOAD",
		4: "INSTALL",
		5: "COLLECT",
		6: "SET_GROUP",
	}
	ProbeCommand_CommandType_value = map[string]int32{
		"LOAD":      0,
		"UNLOAD":    1,
		"RELOAD":    3,
		"INSTALL":   4,
		"COLLECT":   5,
		"SET_GROUP": 6,
	}
)

func (x ProbeCommand_CommandType) Enum() *ProbeCommand_CommandType {
	p := new(ProbeCommand_CommandType)
	*p = x
	return p
}

func (x ProbeCommand_CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProbeCommand_CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[0].Descriptor()
}

func (ProbeCommand_CommandType) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[0]
}

func (x ProbeCommand_CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProbeCommand_CommandType.Descriptor instead.
func (ProbeCommand_CommandType) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6, 0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	KernelVersion string                 `protobuf:"bytes,3,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	IpAddress     string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,5,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	AgentGroup    string                 `protobuf:"bytes,6,opt,name=agent_group,json=agentGroup,proto3" json:"agent_group,omitempty"`
	Framework     *FrameworkInfo         `protobuf:"bytes,7,opt,name=framework,proto3" json:"framework,omitempty"`
	KernelInfo    *KernelInfo            `protobuf:"bytes,8,opt,name=kernel_info,json=kernelInfo,proto3" json:"kernel_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *RegisterRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterRequest) GetAgentGroup() string {
	if x != nil {
		return x.AgentGroup
	}
	return ""
}

func (x *RegisterRequest) GetFramework() *FrameworkInfo {
	if x != nil {
		return x.Framework
	}
	return nil
}

func (x *RegisterRequest) GetKernelInfo() *KernelInfo {
	if x != nil {
		return x.KernelInfo
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AgentToken    string                 `protobuf:"bytes,3,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

type FrameworkInfo struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	BccAvailable           bool                   `protobuf:"varint,1,opt,name=bcc_available,json=bccAvailable,proto3" json:"bcc_available,omitempty"`
	LibbpfAvailable        bool                   `protobuf:"varint,2,opt,name=libbpf_available,json=libbpfAvailable,proto3" json:"libbpf_available,omitempty"`
	LibbpfCore             bool                   `protobuf:"varint,3,opt,name=libbpf_core,json=libbpfCore,proto3" json:"libbpf_core,omitempty"`
	BpftraceAvailable      bool                   `protobuf:"varint,4,opt,name=bpftrace_available,json=bpftraceAvailable,proto3" json:"bpftrace_available,omitempty"`
	ClangAvailable         bool                   `protobuf:"varint,5,opt,name=clang_available,json=clangAvailable,proto3" json:"clang_available,omitempty"`
	LlvmAvailable          bool                   `protobuf:"varint,6,opt,name=llvm_available,json=llvmAvailable,proto3" json:"llvm_available,omitempty"`
	KernelHeadersAvailable bool                   `protobuf:"varint,7,opt,name=kernel_headers_available,json=kernelHeadersAvailable,proto3" json:"kernel_headers_available,omitempty"`
	GoEbpfAvailable        bool                   `protobuf:"varint,8,opt,name=go_ebpf_available,json=goEbpfAvailable,proto3" json:"go_ebpf_available,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FrameworkInfo) Reset() {
	*x = FrameworkInfo{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameworkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameworkInfo) ProtoMessage() {}

func (x *FrameworkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameworkInfo.ProtoReflect.Descriptor instead.
func (*FrameworkInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *FrameworkInfo) GetBccAvailable() bool {
	if x != nil {
		return x.BccAvailable
	}
	return false
}

func (x *FrameworkInfo) GetLibbpfAvailable() bool {
	if x != nil {
		return x.LibbpfAvailable
	}
	return false
}

func (x *FrameworkInfo) GetLibbpfCore() bool {
	if x != nil {
		return x.LibbpfCore
	}
	return false
}

func (x *FrameworkInfo) GetBpftraceAvailable() bool {
	if x != nil {
		return x.BpftraceAvailable
	}
	return false
}

func (x *FrameworkInfo) GetClangAvailable() bool {
	if x != nil {
		return x.ClangAvailable
	}
	return false
}

func (x *FrameworkInfo) GetLlvmAvailable() bool {
	if x != nil {
		return x.LlvmAvailable
	}
	return false
}

func (x *FrameworkInfo) GetKernelHeadersAvailable() bool {
	if x != nil {
		return x.KernelHeadersAvailable
	}
	return false
}

func (x *FrameworkInfo) GetGoEbpfAvailable() bool {
	if x != nil {
		return x.GoEbpfAvailable
	}
	return false
}

type KernelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	BtfEnabled    bool                   `protobuf:"varint,3,opt,name=btf_enabled,json=btfEnabled,proto3" json:"btf_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KernelInfo) Reset() {
	*x = KernelInfo{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelInfo) ProtoMessage() {}

func (x *KernelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelInfo.ProtoReflect.Descriptor instead.
func (*KernelInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *KernelInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *KernelInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *KernelInfo) GetBtfEnabled() bool {
	if x != nil {
		return x.BtfEnabled
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentToken    string                 `protobuf:"bytes,2,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ActiveProbes  int32                  `protobuf:"varint,4,opt,name=active_probes,json=activeProbes,proto3" json:"active_probes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetActiveProbes() int32 {
	if x != nil {
		return x.ActiveProbes
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Commands      []*ProbeCommand        `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetCommands() []*ProbeCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

type ProbeCommand struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Type          ProbeCommand_CommandType `protobuf:"varint,1,opt,name=type,proto3,enum=sentinel.ProbeCommand_CommandType" json:"type,omitempty"`
	ProbeId       string                   `protobuf:"bytes,2,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	ProbeName     string                   `protobuf:"bytes,3,opt,name=probe_name,json=probeName,proto3" json:"probe_name,omitempty"`
	ProbeData     []byte                   `protobuf:"bytes,4,opt,name=probe_data,json=probeData,proto3" json:"probe_data,omitempty"`
	ProbeConfig   string                   `protobuf:"bytes,5,opt,name=probe_config,json=probeConfig,proto3" json:"probe_config,omitempty"`
	GroupName     string                   `protobuf:"bytes,6,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeCommand) Reset() {
	*x = ProbeCommand{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeCommand) ProtoMessage() {}

func (x *ProbeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeCommand.ProtoReflect.Descriptor instead.
func (*ProbeCommand) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ProbeCommand) GetType() ProbeCommand_CommandType {
	if x != nil {
		return x.Type
	}
	return ProbeCommand_LOAD
}

func (x *ProbeCommand) GetProbeId() string {
	if x != nil {
		return x.ProbeId
	}
	return ""
}

func (x *ProbeCommand) GetProbeName() string {
	if x != nil {
		return x.ProbeName
	}
	return ""
}

func (x *ProbeCommand) GetProbeData() []byte {
	if x != nil {
		return x.ProbeData
	}
	return nil
}

func (x *ProbeCommand) GetProbeConfig() string {
	if x != nil {
		return x.ProbeConfig
	}
	return ""
}

func (x *ProbeCommand) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

type ProbeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProbeId       string                 `protobuf:"bytes,1,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	ProbeName     string                 `protobuf:"bytes,2,opt,name=probe_name,json=probeName,proto3" json:"probe_name,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Pid           int32                  `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`
	Comm          string                 `protobuf:"bytes,6,opt,name=comm,proto3" json:"comm,omitempty"`
	Filename      string                 `protobuf:"bytes,7,opt,name=filename,proto3" json:"filename,omitempty"`
	Details       string                 `protobuf:"bytes,8,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeEvent) Reset() {
	*x = ProbeEvent{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeEvent) ProtoMessage() {}

func (x *ProbeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeEvent.ProtoReflect.Descriptor instead.
func (*ProbeEvent) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ProbeEvent) GetProbeId() string {
	if x != nil {
		return x.ProbeId
	}
	return ""
}

func (x *ProbeEvent) GetProbeName() string {
	if x != nil {
		return x.ProbeName
	}
	return ""
}

func (x *ProbeEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ProbeEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ProbeEvent) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProbeEvent) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *ProbeEvent) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ProbeEvent) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type EventReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentToken    string                 `protobuf:"bytes,2,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	Events        []*ProbeEvent          `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventReport) Reset() {
	*x = EventReport{}
	mi := &file_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventReport) ProtoMessage() {}

func (x *EventReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventReport.ProtoReflect.Descriptor instead.
func (*EventReport) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *EventReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EventReport) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

func (x *EventReport) GetEvents() []*ProbeEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// 资产上报
type AssetReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	System         *SystemAsset           `protobuf:"bytes,5,opt,name=system,proto3" json:"system,omitempty"`
	Hardware       *HardwareAsset         `protobuf:"bytes,10,opt,name=hardware,proto3" json:"hardware,omitempty"`
	KernelModules  []*KernelModuleAsset   `protobuf:"bytes,11,rep,name=kernel_modules,json=kernelModules,proto3" json:"kernel_modules,omitempty"`
	EnvVariables   []*EnvVariableAsset    `protobuf:"bytes,12,rep,name=env_variables,json=envVariables,proto3" json:"env_variables,omitempty"`
	DiskUsages     []*DiskUsageAsset      `protobuf:"bytes,13,rep,name=disk_usages,json=diskUsages,proto3" json:"disk_usages,omitempty"`
	NetworkDetails []*NetworkDetailAsset  `protobuf:"bytes,14,rep,name=network_details,json=networkDetails,proto3" json:"network_details,omitempty"`
	ServiceStatus  []*ServiceStatusAsset  `protobuf:"bytes,15,rep,name=service_status,json=serviceStatus,proto3" json:"service_status,omitempty"`
	JarPackages    []*JarPackageAsset     `protobuf:"bytes,16,rep,name=jar_packages,json=jarPackages,proto3" json:"jar_packages,omitempty"`
	PythonPackages []*PythonPackageAsset  `protobuf:"bytes,17,rep,name=python_packages,json=pythonPackages,proto3" json:"python_packages,omitempty"`
	NpmPackages    []*NpmPackageAsset     `protobuf:"bytes,18,rep,name=npm_packages,json=npmPackages,proto3" json:"npm_packages,omitempty"`
	AgentSelf      *AgentSelfAsset        `protobuf:"bytes,19,opt,name=agent_self,json=agentSelf,proto3" json:"agent_self,omitempty"`
	Crons          []*CronAsset           `protobuf:"bytes,6,rep,name=crons,proto3" json:"crons,omitempty"`
	Packages       []*PackageAsset        `protobuf:"bytes,7,rep,name=packages,proto3" json:"packages,omitempty"`
	Services       []*IdentifiedService   `protobuf:"bytes,8,rep,name=services,proto3" json:"services,omitempty"`
	WebComponents  []*WebComponentAsset   `protobuf:"bytes,9,rep,name=web_components,json=webComponents,proto3" json:"web_components,omitempty"`
	Users          []*UserAsset           `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentToken     string                 `protobuf:"bytes,2,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	Processes      []*ProcessAsset        `protobuf:"bytes,3,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AssetReport) Reset() {
	*x = AssetReport{}
	mi := &file_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetReport) ProtoMessage() {}

func (x *AssetReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetReport.ProtoReflect.Descriptor instead.
func (*AssetReport) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *AssetReport) GetSystem() *SystemAsset {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *AssetReport) GetHardware() *HardwareAsset {
	if x != nil {
		return x.Hardware
	}
	return nil
}

func (x *AssetReport) GetKernelModules() []*KernelModuleAsset {
	if x != nil {
		return x.KernelModules
	}
	return nil
}

func (x *AssetReport) GetEnvVariables() []*EnvVariableAsset {
	if x != nil {
		return x.EnvVariables
	}
	return nil
}

func (x *AssetReport) GetDiskUsages() []*DiskUsageAsset {
	if x != nil {
		return x.DiskUsages
	}
	return nil
}

func (x *AssetReport) GetNetworkDetails() []*NetworkDetailAsset {
	if x != nil {
		return x.NetworkDetails
	}
	return nil
}

func (x *AssetReport) GetServiceStatus() []*ServiceStatusAsset {
	if x != nil {
		return x.ServiceStatus
	}
	return nil
}

func (x *AssetReport) GetJarPackages() []*JarPackageAsset {
	if x != nil {
		return x.JarPackages
	}
	return nil
}

func (x *AssetReport) GetPythonPackages() []*PythonPackageAsset {
	if x != nil {
		return x.PythonPackages
	}
	return nil
}

func (x *AssetReport) GetNpmPackages() []*NpmPackageAsset {
	if x != nil {
		return x.NpmPackages
	}
	return nil
}

func (x *AssetReport) GetAgentSelf() *AgentSelfAsset {
	if x != nil {
		return x.AgentSelf
	}
	return nil
}

func (x *AssetReport) GetCrons() []*CronAsset {
	if x != nil {
		return x.Crons
	}
	return nil
}

func (x *AssetReport) GetPackages() []*PackageAsset {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *AssetReport) GetServices() []*IdentifiedService {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *AssetReport) GetWebComponents() []*WebComponentAsset {
	if x != nil {
		return x.WebComponents
	}
	return nil
}

func (x *AssetReport) GetUsers() []*UserAsset {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *AssetReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AssetReport) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

func (x *AssetReport) GetProcesses() []*ProcessAsset {
	if x != nil {
		return x.Processes
	}
	return nil
}

type SystemAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            *OSAsset               `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Cpu           *CPUAsset              `protobuf:"bytes,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        *MemoryAsset           `protobuf:"bytes,3,opt,name=memory,proto3" json:"memory,omitempty"`
	Disks         []*DiskAsset           `protobuf:"bytes,4,rep,name=disks,proto3" json:"disks,omitempty"`
	Networks      []*NetworkAsset        `protobuf:"bytes,5,rep,name=networks,proto3" json:"networks,omitempty"`
	KernelModules []string               `protobuf:"bytes,6,rep,name=kernel_modules,json=kernelModules,proto3" json:"kernel_modules,omitempty"`
	Services      []*ServiceAsset        `protobuf:"bytes,7,rep,name=services,proto3" json:"services,omitempty"`
	Locale        string                 `protobuf:"bytes,8,opt,name=locale,proto3" json:"locale,omitempty"`
	Timezone      string                 `protobuf:"bytes,9,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemAsset) Reset() {
	*x = SystemAsset{}
	mi := &file_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemAsset) ProtoMessage() {}

func (x *SystemAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemAsset.ProtoReflect.Descriptor instead.
func (*SystemAsset) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *SystemAsset) GetOs() *OSAsset {
	if x != nil {
		return x.Os
	}
	return nil
}

func (x *SystemAsset) GetCpu() *CPUAsset {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *SystemAsset) GetMemory() *MemoryAsset {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *SystemAsset) GetDisks() []*DiskAsset {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *SystemAsset) GetNetworks() []*NetworkAsset {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *SystemAsset) GetKernelModules() []string {
	if x != nil {
		return x.KernelModules
	}
	return nil
}

func (x *SystemAsset) GetServices() []*ServiceAsset {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *SystemAsset) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *SystemAsset) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type OSAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Kernel        string                 `protobuf:"bytes,3,opt,name=kernel,proto3" json:"kernel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OSAsset) Reset() {
	*x = OSAsset{}
	mi := &file_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSAsset) ProtoMessage() {}

func (x *OSAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSAsset.ProtoReflect.Descriptor instead.
func (*OSAsset) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *OSAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OSAsset) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *OSAsset) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

type CPUAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Cores         int32                  `protobuf:"varint,2,opt,name=cores,proto3" json:"cores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUAsset) Reset() {
	*x = CPUAsset{}
	mi := &file_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUAsset) ProtoMessage() {}

func (x *CPUAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUAsset.ProtoReflect.Descriptor instead.
func (*CPUAsset) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *CPUAsset) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CPUAsset) GetCores() int32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

type MemoryAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalMb       int32                  `protobuf:"varint,1,opt,name=total_mb,json=totalMb,proto3" json:"total_mb,omitempty"`
	SwapTotalMb   int32                  `protobuf:"varint,2,opt,name=swap_total_mb,json=swapTotalMb,proto3" json:"swap_total_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryAsset) Reset() {
	*x = MemoryAsset{}
	mi := &file_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryAsset) ProtoMessage() {}

func (x *MemoryAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryAsset.ProtoReflect.Descriptor instead.
func (*MemoryAsset) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *MemoryAsset) GetTotalMb() int32 {
	if x != nil {
		return x.TotalMb
	}
	return 0
}

func (x *MemoryAsset) GetSwapTotalMb() int32 {
	if x != nil {
		return x.SwapTotalMb
	}
	return 0
}

type DiskAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountPoint    string                 `protobuf:"bytes,1,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	Filesystem    string                 `protobuf:"bytes,2,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	TotalMb       int32                  `protobuf:"varint,3,opt,name=total_mb,json=totalMb,proto3" json:"total_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskAsset) Reset() {
	*x = DiskAsset{}
	mi := &file_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskAsset) ProtoMessage() {}

func (x *DiskAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskAsset.ProtoReflect.Descriptor instead.
func (*DiskAsset) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{14}
}

func (x *DiskAsset) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *DiskAsset) GetFilesystem() string {
	if x != nil {
		return x.Filesystem
	}
	return ""
}

func (x *DiskAsset) GetTotalMb() int32 {
	if x != nil {
		return x.TotalMb
	}
	return 0
}

type NetworkAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mac           string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	Ips           []string               `protobuf:"bytes,3,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkAsset) Reset() {
	*x = NetworkAsset{}
	mi := &file_proto_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAsset) ProtoMessage() {}

func (x *NetworkAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAsset.ProtoReflect.Descriptor instead.
func (*NetworkAsset) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{15}
}

func (x *NetworkAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkAsset) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *NetworkAsset) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

type WebComponentAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	BasePath      string                 `protobuf:"bytes,4,opt,name=base_path,json=basePath,proto3" json:"base_path,omitempty"`
	ConfigPath    string                 `protobuf:"bytes,5,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	Pid           int32                  `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebComponentAsset) Reset() {
	*x = WebComponentAsset{}
	mi := &file_proto_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebComponentAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebComponentAsset) ProtoMessage() {}

func (x *WebComponentAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebComponentAsset.ProtoReflect.Descriptor instead.
func (*WebComponentAsset) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{16}
}

func (x *WebComponentAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WebComponentAsset) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WebComponentAsset) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *WebComponentAsset) GetBasePath() string {
	if x != nil {
		return x.BasePath
	}
	return ""
}

func (x *WebComponentAsset) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *WebComponentAsset) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type IdentifiedService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Pid           int32                  `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	ExePath       string                 `protobuf:"bytes,5,opt,name=exe_path,json=exePath,proto3" json:"exe_path,omitempty"`
	ConfigPath    string                 `protobuf:"bytes,6,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	ListenPort    []string               `protobuf:"bytes,7,rep,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentifiedService) Reset() {
	*x = IdentifiedService{}
	mi := &file_proto_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifiedService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifiedService) ProtoMessage() {}

func (x *IdentifiedService) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifiedService.ProtoReflect.Descriptor instead.
func (*IdentifiedService) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{17}
}

func (x *IdentifiedService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IdentifiedService) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *IdentifiedService) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IdentifiedService) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *IdentifiedService) GetExePath() string {
	if x != nil {
		return x.ExePath
	}
	return ""
}

func (x *IdentifiedService) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *IdentifiedService) GetListenPort() []string {
	if x != nil {
		return x.ListenPort
	}
	return nil
}

type PackageAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Manager       string                 `protobuf:"bytes,3,opt,name=manager,proto3" json:"manager,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageAsset) Reset() {
	*x = PackageAsset{}
	mi := &file_proto_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageAsset) ProtoMessage() {}

func (x *PackageAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageAsset.ProtoReflect.Descriptor instead.
func (*PackageAsset) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{18}
}

func (x *PackageAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackageAsset) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PackageAsset) GetManager() string {
	if x != nil {
		return x.Manager
	}
	return ""
}

type CronAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Schedule      string                 `protobuf:"bytes,2,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronAsset) Reset() {
	*x = CronAsset{}
	mi := &file_proto_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronAsset) ProtoMessage() {}

func (x *CronAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronAsset.ProtoReflect.Descriptor instead.
func (*CronAsset) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{19}
}

func (x *CronAsset) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *CronAsset) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *CronAsset) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CronAsset) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type HardwareAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manufacturer  string                 `protobuf:"bytes,1,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,3,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Uuid          string                 `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	BootTime      string                 `protobuf:"bytes,5,opt,name=boot_time,json=bootTime,proto3" json:"boot_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HardwareAsset) Reset() {
	*x = HardwareAsset{}
	mi := &file_proto_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareAsset) ProtoMessage() {}

func (x *HardwareAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareAsset.ProtoReflect.Descriptor instead.
func (*HardwareAsset) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{20}
}

func (x *HardwareAsset) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *HardwareAsset) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *HardwareAsset) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *HardwareAsset) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *HardwareAsset) GetBootTime() string {
	if x != nil {
		return x.BootTime
	}
	return ""
}

type KernelModuleAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Size          string                 `protobuf:"bytes,5,opt,name=size,proto3" json:"size,omitempty"`
	UsedBy        int32                  `protobuf:"varint,6,opt,name=used_by,json=usedBy,proto3" json:"used_by,omitempty"`
	Parameters    []string               `protobuf:"bytes,7,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KernelModuleAsset) Reset() {
	*x = KernelModuleAsset{}
	mi := &file_proto_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelModuleAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelModuleAsset) ProtoMessage() {}

func (x *KernelModuleAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelModuleAsset.ProtoReflect.Descriptor instead.
func (*KernelModuleAsset) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{21}
}

func (x *KernelModuleAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KernelModuleAsset) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KernelModuleAsset) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *KernelModuleAsset) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *KernelModuleAsset) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *KernelModuleAsset) GetUsedBy() int32 {
	if x != nil {
		return x.UsedBy
	}
	return 0
}

func (x *KernelModuleAsset) GetParameters() []string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type EnvVariableAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	User          string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvVariableAsset) Reset() {
	*x = EnvVariableAsset{}
	mi := &file_proto_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVariableAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVariableAsset) ProtoMessage() {}

func (x *EnvVariableAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVariableAsset.ProtoReflect.Descriptor instead.
func (*EnvVariableAsset) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{22}
}

func (x *EnvVariableAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvVariableAsset) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *EnvVariableAsset) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EnvVariableAsset) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type DiskUsageAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountPoint    string                 `protobuf:"bytes,1,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	TotalMb       int32                  `protobuf:"varint,2,opt,name=total_mb,json=totalMb,proto3" json:"total_mb,omitempty"`
	UsedMb        int32                  `protobuf:"varint,3,opt,name=used_mb,json=usedMb,proto3" json:"used_mb,omitempty"`
	UsePercent    string                 `protobuf:"bytes,4,opt,name=use_percent,json=usePercent,proto3" json:"use_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskUsageAsset) Reset() {
	*x = DiskUsageAsset{}
	mi := &file_proto_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskUsageAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskUsageAsset) ProtoMessage() {}

func (x *DiskUsageAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskUsageAsset.ProtoReflect.Descriptor instead.
func (*DiskUsageAsset) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{23}
}

func (x *DiskUsageAsset) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *DiskUsageAsset) GetTotalMb() int32 {
	if x != nil {
		return x.TotalMb
	}
	return 0
}

func (x *DiskUsageAsset) GetUsedMb() int32 {
	if x != nil {
		return x.UsedMb
	}
	return 0
}

func (x *DiskUsageAsset) GetUsePercent() string {
	if x != nil {
		return x.UsePercent
	}
	return ""
}

type NetworkDetailAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mac           string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	Ips           []string               `protobuf:"bytes,3,rep,name=ips,proto3" json:"ips,omitempty"`
	Speed         string                 `protobuf:"bytes,4,opt,name=speed,proto3" json:"speed,omitempty"`
	Duplex        string                 `protobuf:"bytes,5,opt,name=duplex,proto3" json:"duplex,omitempty"`
	Mtu           string                 `protobuf:"bytes,6,opt,name=mtu,proto3" json:"mtu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkDetailAsset) Reset() {
	*x = NetworkDetailAsset{}
	mi := &file_proto_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkDetailAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkDetailAsset) ProtoMessage() {}

func (x *NetworkDetailAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkDetailAsset.ProtoReflect.Descriptor instead.
func (*NetworkDetailAsset) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{24}
}

func (x *NetworkDetailAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkDetailAsset) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *NetworkDetailAsset) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *NetworkDetailAsset) GetSpeed() string {
	if x != nil {
		return x.Speed
	}
	return ""
}

func (x *NetworkDetailAsset) GetDuplex() string {
	if x != nil {
		return x.Duplex
	}
	return ""
}

func (x *NetworkDetailAsset) GetMtu() string {
	if x != nil {
		return x.Mtu
	}
	return ""
}

type ServiceStatusAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Active        string                 `protobuf:"bytes,3,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStatusAsset) Reset() {
	*x = ServiceStatusAsset{}
	mi := &file_proto_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatusAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatusAsset) ProtoMessage() {}

func (x *ServiceStatusAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatusAsset.ProtoReflect.Descriptor instead.
func (*ServiceStatusAsset) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{25}
}

func (x *ServiceStatusAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceStatusAsset) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ServiceStatusAsset) GetActive() string {
	if x != nil {
		return x.Active
	}
	return ""
}

type JarPackageAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Executable    bool                   `protobuf:"varint,3,opt,name=executable,proto3" json:"executable,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JarPackageAsset) Reset() {
	*x = JarPackageAsset{}
	mi := &file_proto_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JarPackageAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JarPackageAsset) ProtoMessage() {}

func (x *JarPackageAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JarPackageAsset.ProtoReflect.Descriptor instead.
func (*JarPackageAsset) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{26}
}

func (x *JarPackageAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JarPackageAsset) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *JarPackageAsset) GetExecutable() bool {
	if x != nil {
		return x.Executable
	}
	return false
}

func (x *JarPackageAsset) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *JarPackageAsset) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type PythonPackageAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PythonPackageAsset) Reset() {
	*x = PythonPackageAsset{}
	mi := &file_proto_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PythonPackageAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PythonPackageAsset) ProtoMessage() {}

func (x *PythonPackageAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PythonPackageAsset.ProtoReflect.Descriptor instead.
func (*PythonPackageAsset) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{27}
}

func (x *PythonPackageAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PythonPackageAsset) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PythonPackageAsset) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PythonPackageAsset) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type NpmPackageAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NpmPackageAsset) Reset() {
	*x = NpmPackageAsset{}
	mi := &file_proto_agent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpmPackageAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpmPackageAsset) ProtoMessage() {}

func (x *NpmPackageAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpmPackageAsset.ProtoReflect.Descriptor instead.
func (*NpmPackageAsset) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{28}
}

func (x *NpmPackageAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NpmPackageAsset) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NpmPackageAsset) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *NpmPackageAsset) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type AgentSelfAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstallPath   string                 `protobuf:"bytes,1,opt,name=install_path,json=installPath,proto3" json:"install_path,omitempty"`
	ConfigPath    string                 `protobuf:"bytes,2,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	LogPath       string                 `protobuf:"bytes,3,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"`
	RunUser       string                 `protobuf:"bytes,4,opt,name=run_user,json=runUser,proto3" json:"run_user,omitempty"`
	RunPid        int32                  `protobuf:"varint,5,opt,name=run_pid,json=runPid,proto3" json:"run_pid,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSelfAsset) Reset() {
	*x = AgentSelfAsset{}
	mi := &file_proto_agent_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSelfAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSelfAsset) ProtoMessage() {}

func (x *AgentSelfAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSelfAsset.ProtoReflect.Descriptor instead.
func (*AgentSelfAsset) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{29}
}

func (x *AgentSelfAsset) GetInstallPath() string {
	if x != nil {
		return x.InstallPath
	}
	return ""
}

func (x *AgentSelfAsset) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *AgentSelfAsset) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

func (x *AgentSelfAsset) GetRunUser() string {
	if x != nil {
		return x.RunUser
	}
	return ""
}

func (x *AgentSelfAsset) GetRunPid() int32 {
	if x != nil {
		return x.RunPid
	}
	return 0
}

func (x *AgentSelfAsset) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ServiceAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceAsset) Reset() {
	*x = ServiceAsset{}
	mi := &file_proto_agent_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAsset) ProtoMessage() {}

func (x *ServiceAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAsset.ProtoReflect.Descriptor instead.
func (*ServiceAsset) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{30}
}

func (x *ServiceAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceAsset) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type UserAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Uid           int32                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           int32                  `protobuf:"varint,3,opt,name=gid,proto3" json:"gid,omitempty"`
	Home          string                 `protobuf:"bytes,4,opt,name=home,proto3" json:"home,omitempty"`
	Shell         string                 `protobuf:"bytes,5,opt,name=shell,proto3" json:"shell,omitempty"`
	HasShell      bool                   `protobuf:"varint,6,opt,name=has_shell,json=hasShell,proto3" json:"has_shell,omitempty"`
	IsRoot        bool                   `protobuf:"varint,7,opt,name=is_root,json=isRoot,proto3" json:"is_root,omitempty"`
	IsDisabled    bool                   `protobuf:"varint,8,opt,name=is_disabled,json=isDisabled,proto3" json:"is_disabled,omitempty"`
	HasSudo       bool                   `protobuf:"varint,9,opt,name=has_sudo,json=hasSudo,proto3" json:"has_sudo,omitempty"`
	LastLogin     string                 `protobuf:"bytes,10,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	LastLoginIp   string                 `protobuf:"bytes,11,opt,name=last_login_ip,json=lastLoginIp,proto3" json:"last_login_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAsset) Reset() {
	*x = UserAsset{}
	mi := &file_proto_agent_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAsset) ProtoMessage() {}

func (x *UserAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAsset.ProtoReflect.Descriptor instead.
func (*UserAsset) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{31}
}

func (x *UserAsset) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserAsset) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserAsset) GetGid() int32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *UserAsset) GetHome() string {
	if x != nil {
		return x.Home
	}
	return ""
}

func (x *UserAsset) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

func (x *UserAsset) GetHasShell() bool {
	if x != nil {
		return x.HasShell
	}
	return false
}

func (x *UserAsset) GetIsRoot() bool {
	if x != nil {
		return x.IsRoot
	}
	return false
}

func (x *UserAsset) GetIsDisabled() bool {
	if x != nil {
		return x.IsDisabled
	}
	return false
}

func (x *UserAsset) GetHasSudo() bool {
	if x != nil {
		return x.HasSudo
	}
	return false
}

func (x *UserAsset) GetLastLogin() string {
	if x != nil {
		return x.LastLogin
	}
	return ""
}

func (x *UserAsset) GetLastLoginIp() string {
	if x != nil {
		return x.LastLoginIp
	}
	return ""
}

type ProcessAsset struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Pid            int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid           int32                  `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Cmdline        string                 `protobuf:"bytes,4,opt,name=cmdline,proto3" json:"cmdline,omitempty"`
	ExePath        string                 `protobuf:"bytes,5,opt,name=exe_path,json=exePath,proto3" json:"exe_path,omitempty"`
	User           string                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	State          string                 `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	ListeningPorts []string               `protobuf:"bytes,8,rep,name=listening_ports,json=listeningPorts,proto3" json:"listening_ports,omitempty"`
	StartTime      string                 `protobuf:"bytes,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessAsset) Reset() {
	*x = ProcessAsset{}
	mi := &file_proto_agent_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessAsset) ProtoMessage() {}

func (x *ProcessAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessAsset.ProtoReflect.Descriptor instead.
func (*ProcessAsset) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{32}
}

func (x *ProcessAsset) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessAsset) GetPpid() int32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *ProcessAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessAsset) GetCmdline() string {
	if x != nil {
		return x.Cmdline
	}
	return ""
}

func (x *ProcessAsset) GetExePath() string {
	if x != nil {
		return x.ExePath
	}
	return ""
}

func (x *ProcessAsset) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ProcessAsset) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ProcessAsset) GetListeningPorts() []string {
	if x != nil {
		return x.ListeningPorts
	}
	return nil
}

func (x *ProcessAsset) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\bsentinel\"\xc2\x02\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12%\n" +
	"\x0ekernel_version\x18\x03 \x01(\tR\rkernelVersion\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12#\n" +
	"\ragent_version\x18\x05 \x01(\tR\fagentVersion\x12\x1f\n" +
	"\vagent_group\x18\x06 \x01(\tR\n" +
	"agentGroup\x125\n" +
	"\tframework\x18\a \x01(\v2\x17.sentinel.FrameworkInfoR\tframework\x125\n" +
	"\vkernel_info\x18\b \x01(\v2\x14.sentinel.KernelInfoR\n" +
	"kernelInfo\"g\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vagent_token\x18\x03 \x01(\tR\n" +
	"agentToken\"\xe5\x02\n" +
	"\rFrameworkInfo\x12#\n" +
	"\rbcc_available\x18\x01 \x01(\bR\fbccAvailable\x12)\n" +
	"\x10libbpf_available\x18\x02 \x01(\bR\x0flibbpfAvailable\x12\x1f\n" +
	"\vlibbpf_core\x18\x03 \x01(\bR\n" +
	"libbpfCore\x12-\n" +
	"\x12bpftrace_available\x18\x04 \x01(\bR\x11bpftraceAvailable\x12'\n" +
	"\x0fclang_available\x18\x05 \x01(\bR\x0eclangAvailable\x12%\n" +
	"\x0ellvm_available\x18\x06 \x01(\bR\rllvmAvailable\x128\n" +
	"\x18kernel_headers_available\x18\a \x01(\bR\x16kernelHeadersAvailable\x12*\n" +
	"\x11go_ebpf_available\x18\b \x01(\bR\x0fgoEbpfAvailable\"[\n" +
	"\n" +
	"KernelInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x1f\n" +
	"\vbtf_enabled\x18\x03 \x01(\bR\n" +
	"btfEnabled\"\x91\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vagent_token\x18\x02 \x01(\tR\n" +
	"agentToken\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12#\n" +
	"\ractive_probes\x18\x04 \x01(\x05R\factiveProbes\"a\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x122\n" +
	"\bcommands\x18\x02 \x03(\v2\x16.sentinel.ProbeCommandR\bcommands\"\xbb\x02\n" +
	"\fProbeCommand\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".sentinel.ProbeCommand.CommandTypeR\x04type\x12\x19\n" +
	"\bprobe_id\x18\x02 \x01(\tR\aprobeId\x12\x1d\n" +
	"\n" +
	"probe_name\x18\x03 \x01(\tR\tprobeName\x12\x1d\n" +
	"\n" +
	"probe_data\x18\x04 \x01(\fR\tprobeData\x12!\n" +
	"\fprobe_config\x18\x05 \x01(\tR\vprobeConfig\x12\x1d\n" +
	"\n" +
	"group_name\x18\x06 \x01(\tR\tgroupName\"X\n" +
	"\vCommandType\x12\b\n" +
	"\x04LOAD\x10\x00\x12\n" +
	"\n" +
	"\x06UNLOAD\x10\x01\x12\n" +
	"\n" +
	"\x06RELOAD\x10\x03\x12\v\n" +
	"\aINSTALL\x10\x04\x12\v\n" +
	"\aCOLLECT\x10\x05\x12\r\n" +
	"\tSET_GROUP\x10\x06\"\xdf\x01\n" +
	"\n" +
	"ProbeEvent\x12\x19\n" +
	"\bprobe_id\x18\x01 \x01(\tR\aprobeId\x12\x1d\n" +
	"\n" +
	"probe_name\x18\x02 \x01(\tR\tprobeName\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04comm\x18\x06 \x01(\tR\x04comm\x12\x1a\n" +
	"\bfilename\x18\a \x01(\tR\bfilename\x12\x18\n" +
	"\adetails\x18\b \x01(\tR\adetails\"w\n" +
	"\vEventReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vagent_token\x18\x02 \x01(\tR\n" +
	"agentToken\x12,\n" +
	"\x06events\x18\x03 \x03(\v2\x14.sentinel.ProbeEventR\x06events\"\xb2\b\n" +
	"\vAssetReport\x12-\n" +
	"\x06system\x18\x05 \x01(\v2\x15.sentinel.SystemAssetR\x06system\x123\n" +
	"\bhardware\x18\n" +
	" \x01(\v2\x17.sentinel.HardwareAssetR\bhardware\x12B\n" +
	"\x0ekernel_modules\x18\v \x03(\v2\x1b.sentinel.KernelModuleAssetR\rkernelModules\x12?\n" +
	"\renv_variables\x18\f \x03(\v2\x1a.sentinel.EnvVariableAssetR\fenvVariables\x129\n" +
	"\vdisk_usages\x18\r \x03(\v2\x18.sentinel.DiskUsageAssetR\n" +
	"diskUsages\x12E\n" +
	"\x0fnetwork_details\x18\x0e \x03(\v2\x1c.sentinel.NetworkDetailAssetR\x0enetworkDetails\x12C\n" +
	"\x0eservice_status\x18\x0f \x03(\v2\x1c.sentinel.ServiceStatusAssetR\rserviceStatus\x12<\n" +
	"\fjar_packages\x18\x10 \x03(\v2\x19.sentinel.JarPackageAssetR\vjarPackages\x12E\n" +
	"\x0fpython_packages\x18\x11 \x03(\v2\x1c.sentinel.PythonPackageAssetR\x0epythonPackages\x12<\n" +
	"\fnpm_packages\x18\x12 \x03(\v2\x19.sentinel.NpmPackageAssetR\vnpmPackages\x127\n" +
	"\n" +
	"agent_self\x18\x13 \x01(\v2\x18.sentinel.AgentSelfAssetR\tagentSelf\x12)\n" +
	"\x05crons\x18\x06 \x03(\v2\x13.sentinel.CronAssetR\x05crons\x122\n" +
	"\bpackages\x18\a \x03(\v2\x16.sentinel.PackageAssetR\bpackages\x127\n" +
	"\bservices\x18\b \x03(\v2\x1b.sentinel.IdentifiedServiceR\bservices\x12B\n" +
	"\x0eweb_components\x18\t \x03(\v2\x1b.sentinel.WebComponentAssetR\rwebComponents\x12)\n" +
	"\x05users\x18\x04 \x03(\v2\x13.sentinel.UserAssetR\x05users\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vagent_token\x18\x02 \x01(\tR\n" +
	"agentToken\x124\n" +
	"\tprocesses\x18\x03 \x03(\v2\x16.sentinel.ProcessAssetR\tprocesses\"\xf3\x02\n" +
	"\vSystemAsset\x12!\n" +
	"\x02os\x18\x01 \x01(\v2\x11.sentinel.OSAssetR\x02os\x12$\n" +
	"\x03cpu\x18\x02 \x01(\v2\x12.sentinel.CPUAssetR\x03cpu\x12-\n" +
	"\x06memory\x18\x03 \x01(\v2\x15.sentinel.MemoryAssetR\x06memory\x12)\n" +
	"\x05disks\x18\x04 \x03(\v2\x13.sentinel.DiskAssetR\x05disks\x122\n" +
	"\bnetworks\x18\x05 \x03(\v2\x16.sentinel.NetworkAssetR\bnetworks\x12%\n" +
	"\x0ekernel_modules\x18\x06 \x03(\tR\rkernelModules\x122\n" +
	"\bservices\x18\a \x03(\v2\x16.sentinel.ServiceAssetR\bservices\x12\x16\n" +
	"\x06locale\x18\b \x01(\tR\x06locale\x12\x1a\n" +
	"\btimezone\x18\t \x01(\tR\btimezone\"O\n" +
	"\aOSAsset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06kernel\x18\x03 \x01(\tR\x06kernel\"6\n" +
	"\bCPUAsset\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x14\n" +
	"\x05cores\x18\x02 \x01(\x05R\x05cores\"L\n" +
	"\vMemoryAsset\x12\x19\n" +
	"\btotal_mb\x18\x01 \x01(\x05R\atotalMb\x12\"\n" +
	"\rswap_total_mb\x18\x02 \x01(\x05R\vswapTotalMb\"g\n" +
	"\tDiskAsset\x12\x1f\n" +
	"\vmount_point\x18\x01 \x01(\tR\n" +
	"mountPoint\x12\x1e\n" +
	"\n" +
	"filesystem\x18\x02 \x01(\tR\n" +
	"filesystem\x12\x19\n" +
	"\btotal_mb\x18\x03 \x01(\x05R\atotalMb\"F\n" +
	"\fNetworkAsset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\x12\x10\n" +
	"\x03ips\x18\x03 \x03(\tR\x03ips\"\xa5\x01\n" +
	"\x11WebComponentAsset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1b\n" +
	"\tbase_path\x18\x04 \x01(\tR\bbasePath\x12\x1f\n" +
	"\vconfig_path\x18\x05 \x01(\tR\n" +
	"configPath\x12\x10\n" +
	"\x03pid\x18\x06 \x01(\x05R\x03pid\"\xc4\x01\n" +
	"\x11IdentifiedService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\x05R\x03pid\x12\x19\n" +
	"\bexe_path\x18\x05 \x01(\tR\aexePath\x12\x1f\n" +
	"\vconfig_path\x18\x06 \x01(\tR\n" +
	"configPath\x12\x1f\n" +
	"\vlisten_port\x18\a \x03(\tR\n" +
	"listenPort\"V\n" +
	"\fPackageAsset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x18\n" +
	"\amanager\x18\x03 \x01(\tR\amanager\"m\n" +
	"\tCronAsset\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1a\n" +
	"\bschedule\x18\x02 \x01(\tR\bschedule\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"\x9f\x01\n" +
	"\rHardwareAsset\x12\"\n" +
	"\fmanufacturer\x18\x01 \x01(\tR\fmanufacturer\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12#\n" +
	"\rserial_number\x18\x03 \x01(\tR\fserialNumber\x12\x12\n" +
	"\x04uuid\x18\x04 \x01(\tR\x04uuid\x12\x1b\n" +
	"\tboot_time\x18\x05 \x01(\tR\bbootTime\"\xc4\x01\n" +
	"\x11KernelModuleAsset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x12\n" +
	"\x04size\x18\x05 \x01(\tR\x04size\x12\x17\n" +
	"\aused_by\x18\x06 \x01(\x05R\x06usedBy\x12\x1e\n" +
	"\n" +
	"parameters\x18\a \x03(\tR\n" +
	"parameters\"d\n" +
	"\x10EnvVariableAsset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\"\x86\x01\n" +
	"\x0eDiskUsageAsset\x12\x1f\n" +
	"\vmount_point\x18\x01 \x01(\tR\n" +
	"mountPoint\x12\x19\n" +
	"\btotal_mb\x18\x02 \x01(\x05R\atotalMb\x12\x17\n" +
	"\aused_mb\x18\x03 \x01(\x05R\x06usedMb\x12\x1f\n" +
	"\vuse_percent\x18\x04 \x01(\tR\n" +
	"usePercent\"\x8c\x01\n" +
	"\x12NetworkDetailAsset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\x12\x10\n" +
	"\x03ips\x18\x03 \x03(\tR\x03ips\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\tR\x05speed\x12\x16\n" +
	"\x06duplex\x18\x05 \x01(\tR\x06duplex\x12\x10\n" +
	"\x03mtu\x18\x06 \x01(\tR\x03mtu\"Z\n" +
	"\x12ServiceStatusAsset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12\x16\n" +
	"\x06active\x18\x03 \x01(\tR\x06active\"\x87\x01\n" +
	"\x0fJarPackageAsset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"executable\x18\x03 \x01(\bR\n" +
	"executable\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\"l\n" +
	"\x12PythonPackageAsset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\"i\n" +
	"\x0fNpmPackageAsset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\"\xbd\x01\n" +
	"\x0eAgentSelfAsset\x12!\n" +
	"\finstall_path\x18\x01 \x01(\tR\vinstallPath\x12\x1f\n" +
	"\vconfig_path\x18\x02 \x01(\tR\n" +
	"configPath\x12\x19\n" +
	"\blog_path\x18\x03 \x01(\tR\alogPath\x12\x19\n" +
	"\brun_user\x18\x04 \x01(\tR\arunUser\x12\x17\n" +
	"\arun_pid\x18\x05 \x01(\x05R\x06runPid\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\"<\n" +
	"\fServiceAsset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"\xaa\x02\n" +
	"\tUserAsset\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x05R\x03uid\x12\x10\n" +
	"\x03gid\x18\x03 \x01(\x05R\x03gid\x12\x12\n" +
	"\x04home\x18\x04 \x01(\tR\x04home\x12\x14\n" +
	"\x05shell\x18\x05 \x01(\tR\x05shell\x12\x1b\n" +
	"\thas_shell\x18\x06 \x01(\bR\bhasShell\x12\x17\n" +
	"\ais_root\x18\a \x01(\bR\x06isRoot\x12\x1f\n" +
	"\vis_disabled\x18\b \x01(\bR\n" +
	"isDisabled\x12\x19\n" +
	"\bhas_sudo\x18\t \x01(\bR\ahasSudo\x12\x1d\n" +
	"\n" +
	"last_login\x18\n" +
	" \x01(\tR\tlastLogin\x12\"\n" +
	"\rlast_login_ip\x18\v \x01(\tR\vlastLoginIp\"\xef\x01\n" +
	"\fProcessAsset\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04ppid\x18\x02 \x01(\x05R\x04ppid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\acmdline\x18\x04 \x01(\tR\acmdline\x12\x19\n" +
	"\bexe_path\x18\x05 \x01(\tR\aexePath\x12\x12\n" +
	"\x04user\x18\x06 \x01(\tR\x04user\x12\x14\n" +
	"\x05state\x18\a \x01(\tR\x05state\x12'\n" +
	"\x0flistening_ports\x18\b \x03(\tR\x0elisteningPorts\x12\x1d\n" +
	"\n" +
	"start_time\x18\t \x01(\tR\tstartTime2\x9f\x02\n" +
	"\bSentinel\x12A\n" +
	"\bRegister\x12\x19.sentinel.RegisterRequest\x1a\x1a.sentinel.RegisterResponse\x12H\n" +
	"\tHeartbeat\x12\x1a.sentinel.HeartbeatRequest\x1a\x1b.sentinel.HeartbeatResponse(\x010\x01\x12B\n" +
	"\fReportEvents\x12\x15.sentinel.EventReport\x1a\x1b.sentinel.HeartbeatResponse\x12B\n" +
	"\fReportAssets\x12\x15.sentinel.AssetReport\x1a\x1b.sentinel.HeartbeatResponseB.Z,github.com/CoderXinNing/ebpf-system/proto/pbb\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_proto_agent_proto_goTypes = []any{
	(ProbeCommand_CommandType)(0), // 0: sentinel.ProbeCommand.CommandType
	(*RegisterRequest)(nil),       // 1: sentinel.RegisterRequest
	(*RegisterResponse)(nil),      // 2: sentinel.RegisterResponse
	(*FrameworkInfo)(nil),         // 3: sentinel.FrameworkInfo
	(*KernelInfo)(nil),            // 4: sentinel.KernelInfo
	(*HeartbeatRequest)(nil),      // 5: sentinel.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 6: sentinel.HeartbeatResponse
	(*ProbeCommand)(nil),          // 7: sentinel.ProbeCommand
	(*ProbeEvent)(nil),            // 8: sentinel.ProbeEvent
	(*EventReport)(nil),           // 9: sentinel.EventReport
	(*AssetReport)(nil),           // 10: sentinel.AssetReport
	(*SystemAsset)(nil),           // 11: sentinel.SystemAsset
	(*OSAsset)(nil),               // 12: sentinel.OSAsset
	(*CPUAsset)(nil),              // 13: sentinel.CPUAsset
	(*MemoryAsset)(nil),           // 14: sentinel.MemoryAsset
	(*DiskAsset)(nil),             // 15: sentinel.DiskAsset
	(*NetworkAsset)(nil),          // 16: sentinel.NetworkAsset
	(*WebComponentAsset)(nil),     // 17: sentinel.WebComponentAsset
	(*IdentifiedService)(nil),     // 18: sentinel.IdentifiedService
	(*PackageAsset)(nil),          // 19: sentinel.PackageAsset
	(*CronAsset)(nil),             // 20: sentinel.CronAsset
	(*HardwareAsset)(nil),         // 21: sentinel.HardwareAsset
	(*KernelModuleAsset)(nil),     // 22: sentinel.KernelModuleAsset
	(*EnvVariableAsset)(nil),      // 23: sentinel.EnvVariableAsset
	(*DiskUsageAsset)(nil),        // 24: sentinel.DiskUsageAsset
	(*NetworkDetailAsset)(nil),    // 25: sentinel.NetworkDetailAsset
	(*ServiceStatusAsset)(nil),    // 26: sentinel.ServiceStatusAsset
	(*JarPackageAsset)(nil),       // 27: sentinel.JarPackageAsset
	(*PythonPackageAsset)(nil),    // 28: sentinel.PythonPackageAsset
	(*NpmPackageAsset)(nil),       // 29: sentinel.NpmPackageAsset
	(*AgentSelfAsset)(nil),        // 30: sentinel.AgentSelfAsset
	(*ServiceAsset)(nil),          // 31: sentinel.ServiceAsset
	(*UserAsset)(nil),             // 32: sentinel.UserAsset
	(*ProcessAsset)(nil),          // 33: sentinel.ProcessAsset
}
var file_proto_agent_proto_depIdxs = []int32{
	3,  // 0: sentinel.RegisterRequest.framework:type_name -> sentinel.FrameworkInfo
	4,  // 1: sentinel.RegisterRequest.kernel_info:type_name -> sentinel.KernelInfo
	7,  // 2: sentinel.HeartbeatResponse.commands:type_name -> sentinel.ProbeCommand
	0,  // 3: sentinel.ProbeCommand.type:type_name -> sentinel.ProbeCommand.CommandType
	8,  // 4: sentinel.EventReport.events:type_name -> sentinel.ProbeEvent
	11, // 5: sentinel.AssetReport.system:type_name -> sentinel.SystemAsset
	21, // 6: sentinel.AssetReport.hardware:type_name -> sentinel.HardwareAsset
	22, // 7: sentinel.AssetReport.kernel_modules:type_name -> sentinel.KernelModuleAsset
	23, // 8: sentinel.AssetReport.env_variables:type_name -> sentinel.EnvVariableAsset
	24, // 9: sentinel.AssetReport.disk_usages:type_name -> sentinel.DiskUsageAsset
	25, // 10: sentinel.AssetReport.network_details:type_name -> sentinel.NetworkDetailAsset
	26, // 11: sentinel.AssetReport.service_status:type_name -> sentinel.ServiceStatusAsset
	27, // 12: sentinel.AssetReport.jar_packages:type_name -> sentinel.JarPackageAsset
	28, // 13: sentinel.AssetReport.python_packages:type_name -> sentinel.PythonPackageAsset
	29, // 14: sentinel.AssetReport.npm_packages:type_name -> sentinel.NpmPackageAsset
	30, // 15: sentinel.AssetReport.agent_self:type_name -> sentinel.AgentSelfAsset
	20, // 16: sentinel.AssetReport.crons:type_name -> sentinel.CronAsset
	19, // 17: sentinel.AssetReport.packages:type_name -> sentinel.PackageAsset
	18, // 18: sentinel.AssetReport.services:type_name -> sentinel.IdentifiedService
	17, // 19: sentinel.AssetReport.web_components:type_name -> sentinel.WebComponentAsset
	32, // 20: sentinel.AssetReport.users:type_name -> sentinel.UserAsset
	33, // 21: sentinel.AssetReport.processes:type_name -> sentinel.ProcessAsset
	12, // 22: sentinel.SystemAsset.os:type_name -> sentinel.OSAsset
	13, // 23: sentinel.SystemAsset.cpu:type_name -> sentinel.CPUAsset
	14, // 24: sentinel.SystemAsset.memory:type_name -> sentinel.MemoryAsset
	15, // 25: sentinel.SystemAsset.disks:type_name -> sentinel.DiskAsset
	16, // 26: sentinel.SystemAsset.networks:type_name -> sentinel.NetworkAsset
	31, // 27: sentinel.SystemAsset.services:type_name -> sentinel.ServiceAsset
	1,  // 28: sentinel.Sentinel.Register:input_type -> sentinel.RegisterRequest
	5,  // 29: sentinel.Sentinel.Heartbeat:input_type -> sentinel.HeartbeatRequest
	9,  // 30: sentinel.Sentinel.ReportEvents:input_type -> sentinel.EventReport
	10, // 31: sentinel.Sentinel.ReportAssets:input_type -> sentinel.AssetReport
	2,  // 32: sentinel.Sentinel.Register:output_type -> sentinel.RegisterResponse
	6,  // 33: sentinel.Sentinel.Heartbeat:output_type -> sentinel.HeartbeatResponse
	6,  // 34: sentinel.Sentinel.ReportEvents:output_type -> sentinel.HeartbeatResponse
	6,  // 35: sentinel.Sentinel.ReportAssets:output_type -> sentinel.HeartbeatResponse
	32, // [32:36] is the sub-list for method output_type
	28, // [28:32] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
