// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.12.4
// source: asset.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---- 进程资产 ----
type ProcessAsset struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Pid            int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid           int32                  `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Cmdline        string                 `protobuf:"bytes,4,opt,name=cmdline,proto3" json:"cmdline,omitempty"`
	ExePath        string                 `protobuf:"bytes,5,opt,name=exe_path,json=exePath,proto3" json:"exe_path,omitempty"`
	User           string                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	State          string                 `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	ListeningPorts []string               `protobuf:"bytes,8,rep,name=listening_ports,json=listeningPorts,proto3" json:"listening_ports,omitempty"`
	StartTime      string                 `protobuf:"bytes,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessAsset) Reset() {
	*x = ProcessAsset{}
	mi := &file_asset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessAsset) ProtoMessage() {}

func (x *ProcessAsset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessAsset.ProtoReflect.Descriptor instead.
func (*ProcessAsset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessAsset) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessAsset) GetPpid() int32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *ProcessAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessAsset) GetCmdline() string {
	if x != nil {
		return x.Cmdline
	}
	return ""
}

func (x *ProcessAsset) GetExePath() string {
	if x != nil {
		return x.ExePath
	}
	return ""
}

func (x *ProcessAsset) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ProcessAsset) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ProcessAsset) GetListeningPorts() []string {
	if x != nil {
		return x.ListeningPorts
	}
	return nil
}

func (x *ProcessAsset) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

type ProcessReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Processes     []*ProcessAsset        `protobuf:"bytes,2,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessReport) Reset() {
	*x = ProcessReport{}
	mi := &file_asset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessReport) ProtoMessage() {}

func (x *ProcessReport) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessReport.ProtoReflect.Descriptor instead.
func (*ProcessReport) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ProcessReport) GetProcesses() []*ProcessAsset {
	if x != nil {
		return x.Processes
	}
	return nil
}

// ---- 用户资产 ----
type UserAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Uid           int32                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           int32                  `protobuf:"varint,3,opt,name=gid,proto3" json:"gid,omitempty"`
	Home          string                 `protobuf:"bytes,4,opt,name=home,proto3" json:"home,omitempty"`
	Shell         string                 `protobuf:"bytes,5,opt,name=shell,proto3" json:"shell,omitempty"`
	HasShell      bool                   `protobuf:"varint,6,opt,name=has_shell,json=hasShell,proto3" json:"has_shell,omitempty"`
	IsRoot        bool                   `protobuf:"varint,7,opt,name=is_root,json=isRoot,proto3" json:"is_root,omitempty"`
	IsDisabled    bool                   `protobuf:"varint,8,opt,name=is_disabled,json=isDisabled,proto3" json:"is_disabled,omitempty"`
	HasSudo       bool                   `protobuf:"varint,9,opt,name=has_sudo,json=hasSudo,proto3" json:"has_sudo,omitempty"`
	LastLogin     string                 `protobuf:"bytes,10,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	LastLoginIp   string                 `protobuf:"bytes,11,opt,name=last_login_ip,json=lastLoginIp,proto3" json:"last_login_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAsset) Reset() {
	*x = UserAsset{}
	mi := &file_asset_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAsset) ProtoMessage() {}

func (x *UserAsset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAsset.ProtoReflect.Descriptor instead.
func (*UserAsset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{2}
}

func (x *UserAsset) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserAsset) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserAsset) GetGid() int32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *UserAsset) GetHome() string {
	if x != nil {
		return x.Home
	}
	return ""
}

func (x *UserAsset) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

func (x *UserAsset) GetHasShell() bool {
	if x != nil {
		return x.HasShell
	}
	return false
}

func (x *UserAsset) GetIsRoot() bool {
	if x != nil {
		return x.IsRoot
	}
	return false
}

func (x *UserAsset) GetIsDisabled() bool {
	if x != nil {
		return x.IsDisabled
	}
	return false
}

func (x *UserAsset) GetHasSudo() bool {
	if x != nil {
		return x.HasSudo
	}
	return false
}

func (x *UserAsset) GetLastLogin() string {
	if x != nil {
		return x.LastLogin
	}
	return ""
}

func (x *UserAsset) GetLastLoginIp() string {
	if x != nil {
		return x.LastLoginIp
	}
	return ""
}

type UserReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Users         []*UserAsset           `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReport) Reset() {
	*x = UserReport{}
	mi := &file_asset_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReport) ProtoMessage() {}

func (x *UserReport) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReport.ProtoReflect.Descriptor instead.
func (*UserReport) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{3}
}

func (x *UserReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UserReport) GetUsers() []*UserAsset {
	if x != nil {
		return x.Users
	}
	return nil
}

// ---- 系统信息 ----
type SystemAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            *OSAsset               `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Cpu           *CPUAsset              `protobuf:"bytes,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        *MemoryAsset           `protobuf:"bytes,3,opt,name=memory,proto3" json:"memory,omitempty"`
	Disks         []*DiskAsset           `protobuf:"bytes,4,rep,name=disks,proto3" json:"disks,omitempty"`
	Networks      []*NetworkAsset        `protobuf:"bytes,5,rep,name=networks,proto3" json:"networks,omitempty"`
	KernelModules []string               `protobuf:"bytes,6,rep,name=kernel_modules,json=kernelModules,proto3" json:"kernel_modules,omitempty"`
	Services      []*ServiceAsset        `protobuf:"bytes,7,rep,name=services,proto3" json:"services,omitempty"`
	Locale        string                 `protobuf:"bytes,8,opt,name=locale,proto3" json:"locale,omitempty"`
	Timezone      string                 `protobuf:"bytes,9,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemAsset) Reset() {
	*x = SystemAsset{}
	mi := &file_asset_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemAsset) ProtoMessage() {}

func (x *SystemAsset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemAsset.ProtoReflect.Descriptor instead.
func (*SystemAsset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{4}
}

func (x *SystemAsset) GetOs() *OSAsset {
	if x != nil {
		return x.Os
	}
	return nil
}

func (x *SystemAsset) GetCpu() *CPUAsset {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *SystemAsset) GetMemory() *MemoryAsset {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *SystemAsset) GetDisks() []*DiskAsset {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *SystemAsset) GetNetworks() []*NetworkAsset {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *SystemAsset) GetKernelModules() []string {
	if x != nil {
		return x.KernelModules
	}
	return nil
}

func (x *SystemAsset) GetServices() []*ServiceAsset {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *SystemAsset) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *SystemAsset) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type OSAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Kernel        string                 `protobuf:"bytes,3,opt,name=kernel,proto3" json:"kernel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OSAsset) Reset() {
	*x = OSAsset{}
	mi := &file_asset_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSAsset) ProtoMessage() {}

func (x *OSAsset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSAsset.ProtoReflect.Descriptor instead.
func (*OSAsset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{5}
}

func (x *OSAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OSAsset) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *OSAsset) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

type CPUAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Cores         int32                  `protobuf:"varint,2,opt,name=cores,proto3" json:"cores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUAsset) Reset() {
	*x = CPUAsset{}
	mi := &file_asset_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUAsset) ProtoMessage() {}

func (x *CPUAsset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUAsset.ProtoReflect.Descriptor instead.
func (*CPUAsset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{6}
}

func (x *CPUAsset) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CPUAsset) GetCores() int32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

type MemoryAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalMb       int32                  `protobuf:"varint,1,opt,name=total_mb,json=totalMb,proto3" json:"total_mb,omitempty"`
	SwapTotalMb   int32                  `protobuf:"varint,2,opt,name=swap_total_mb,json=swapTotalMb,proto3" json:"swap_total_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryAsset) Reset() {
	*x = MemoryAsset{}
	mi := &file_asset_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryAsset) ProtoMessage() {}

func (x *MemoryAsset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryAsset.ProtoReflect.Descriptor instead.
func (*MemoryAsset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{7}
}

func (x *MemoryAsset) GetTotalMb() int32 {
	if x != nil {
		return x.TotalMb
	}
	return 0
}

func (x *MemoryAsset) GetSwapTotalMb() int32 {
	if x != nil {
		return x.SwapTotalMb
	}
	return 0
}

type DiskAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountPoint    string                 `protobuf:"bytes,1,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	Filesystem    string                 `protobuf:"bytes,2,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	TotalMb       int32                  `protobuf:"varint,3,opt,name=total_mb,json=totalMb,proto3" json:"total_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskAsset) Reset() {
	*x = DiskAsset{}
	mi := &file_asset_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskAsset) ProtoMessage() {}

func (x *DiskAsset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskAsset.ProtoReflect.Descriptor instead.
func (*DiskAsset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{8}
}

func (x *DiskAsset) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *DiskAsset) GetFilesystem() string {
	if x != nil {
		return x.Filesystem
	}
	return ""
}

func (x *DiskAsset) GetTotalMb() int32 {
	if x != nil {
		return x.TotalMb
	}
	return 0
}

type NetworkAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mac           string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	Ips           []string               `protobuf:"bytes,3,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkAsset) Reset() {
	*x = NetworkAsset{}
	mi := &file_asset_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAsset) ProtoMessage() {}

func (x *NetworkAsset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAsset.ProtoReflect.Descriptor instead.
func (*NetworkAsset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{9}
}

func (x *NetworkAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkAsset) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *NetworkAsset) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

type ServiceAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceAsset) Reset() {
	*x = ServiceAsset{}
	mi := &file_asset_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAsset) ProtoMessage() {}

func (x *ServiceAsset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAsset.ProtoReflect.Descriptor instead.
func (*ServiceAsset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{10}
}

func (x *ServiceAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceAsset) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SystemReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	System        *SystemAsset           `protobuf:"bytes,2,opt,name=system,proto3" json:"system,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemReport) Reset() {
	*x = SystemReport{}
	mi := &file_asset_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemReport) ProtoMessage() {}

func (x *SystemReport) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemReport.ProtoReflect.Descriptor instead.
func (*SystemReport) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{11}
}

func (x *SystemReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SystemReport) GetSystem() *SystemAsset {
	if x != nil {
		return x.System
	}
	return nil
}

// ---- 软件包 ----
type PackageAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Manager       string                 `protobuf:"bytes,3,opt,name=manager,proto3" json:"manager,omitempty"`
	SizeKb        int64                  `protobuf:"varint,4,opt,name=size_kb,json=sizeKb,proto3" json:"size_kb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageAsset) Reset() {
	*x = PackageAsset{}
	mi := &file_asset_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageAsset) ProtoMessage() {}

func (x *PackageAsset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageAsset.ProtoReflect.Descriptor instead.
func (*PackageAsset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{12}
}

func (x *PackageAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackageAsset) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PackageAsset) GetManager() string {
	if x != nil {
		return x.Manager
	}
	return ""
}

func (x *PackageAsset) GetSizeKb() int64 {
	if x != nil {
		return x.SizeKb
	}
	return 0
}

type PackageReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Packages       []*PackageAsset        `protobuf:"bytes,2,rep,name=packages,proto3" json:"packages,omitempty"`
	JarPackages    []*JarPackageAsset     `protobuf:"bytes,3,rep,name=jar_packages,json=jarPackages,proto3" json:"jar_packages,omitempty"`
	PythonPackages []*PythonPackageAsset  `protobuf:"bytes,4,rep,name=python_packages,json=pythonPackages,proto3" json:"python_packages,omitempty"`
	NpmPackages    []*NpmPackageAsset     `protobuf:"bytes,5,rep,name=npm_packages,json=npmPackages,proto3" json:"npm_packages,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PackageReport) Reset() {
	*x = PackageReport{}
	mi := &file_asset_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageReport) ProtoMessage() {}

func (x *PackageReport) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageReport.ProtoReflect.Descriptor instead.
func (*PackageReport) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{13}
}

func (x *PackageReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PackageReport) GetPackages() []*PackageAsset {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *PackageReport) GetJarPackages() []*JarPackageAsset {
	if x != nil {
		return x.JarPackages
	}
	return nil
}

func (x *PackageReport) GetPythonPackages() []*PythonPackageAsset {
	if x != nil {
		return x.PythonPackages
	}
	return nil
}

func (x *PackageReport) GetNpmPackages() []*NpmPackageAsset {
	if x != nil {
		return x.NpmPackages
	}
	return nil
}

type JarPackageAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Executable    bool                   `protobuf:"varint,3,opt,name=executable,proto3" json:"executable,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JarPackageAsset) Reset() {
	*x = JarPackageAsset{}
	mi := &file_asset_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JarPackageAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JarPackageAsset) ProtoMessage() {}

func (x *JarPackageAsset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JarPackageAsset.ProtoReflect.Descriptor instead.
func (*JarPackageAsset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{14}
}

func (x *JarPackageAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JarPackageAsset) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *JarPackageAsset) GetExecutable() bool {
	if x != nil {
		return x.Executable
	}
	return false
}

func (x *JarPackageAsset) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *JarPackageAsset) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type PythonPackageAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PythonPackageAsset) Reset() {
	*x = PythonPackageAsset{}
	mi := &file_asset_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PythonPackageAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PythonPackageAsset) ProtoMessage() {}

func (x *PythonPackageAsset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PythonPackageAsset.ProtoReflect.Descriptor instead.
func (*PythonPackageAsset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{15}
}

func (x *PythonPackageAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PythonPackageAsset) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PythonPackageAsset) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PythonPackageAsset) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type NpmPackageAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NpmPackageAsset) Reset() {
	*x = NpmPackageAsset{}
	mi := &file_asset_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpmPackageAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpmPackageAsset) ProtoMessage() {}

func (x *NpmPackageAsset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpmPackageAsset.ProtoReflect.Descriptor instead.
func (*NpmPackageAsset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{16}
}

func (x *NpmPackageAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NpmPackageAsset) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NpmPackageAsset) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *NpmPackageAsset) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

// ---- 定时任务 ----
type CronAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Schedule      string                 `protobuf:"bytes,2,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronAsset) Reset() {
	*x = CronAsset{}
	mi := &file_asset_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronAsset) ProtoMessage() {}

func (x *CronAsset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronAsset.ProtoReflect.Descriptor instead.
func (*CronAsset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{17}
}

func (x *CronAsset) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *CronAsset) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *CronAsset) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CronAsset) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type CronReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Crons         []*CronAsset           `protobuf:"bytes,2,rep,name=crons,proto3" json:"crons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronReport) Reset() {
	*x = CronReport{}
	mi := &file_asset_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronReport) ProtoMessage() {}

func (x *CronReport) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronReport.ProtoReflect.Descriptor instead.
func (*CronReport) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{18}
}

func (x *CronReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CronReport) GetCrons() []*CronAsset {
	if x != nil {
		return x.Crons
	}
	return nil
}

// ---- 服务识别 ----
type IdentifiedService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Pid           int32                  `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	ExePath       string                 `protobuf:"bytes,5,opt,name=exe_path,json=exePath,proto3" json:"exe_path,omitempty"`
	ConfigPath    string                 `protobuf:"bytes,6,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	ListenPort    []string               `protobuf:"bytes,7,rep,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentifiedService) Reset() {
	*x = IdentifiedService{}
	mi := &file_asset_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifiedService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifiedService) ProtoMessage() {}

func (x *IdentifiedService) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifiedService.ProtoReflect.Descriptor instead.
func (*IdentifiedService) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{19}
}

func (x *IdentifiedService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IdentifiedService) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *IdentifiedService) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IdentifiedService) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *IdentifiedService) GetExePath() string {
	if x != nil {
		return x.ExePath
	}
	return ""
}

func (x *IdentifiedService) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *IdentifiedService) GetListenPort() []string {
	if x != nil {
		return x.ListenPort
	}
	return nil
}

type ServiceReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Services      []*IdentifiedService   `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	ServiceStatus []*ServiceStatusAsset  `protobuf:"bytes,3,rep,name=service_status,json=serviceStatus,proto3" json:"service_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceReport) Reset() {
	*x = ServiceReport{}
	mi := &file_asset_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceReport) ProtoMessage() {}

func (x *ServiceReport) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceReport.ProtoReflect.Descriptor instead.
func (*ServiceReport) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{20}
}

func (x *ServiceReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ServiceReport) GetServices() []*IdentifiedService {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ServiceReport) GetServiceStatus() []*ServiceStatusAsset {
	if x != nil {
		return x.ServiceStatus
	}
	return nil
}

type ServiceStatusAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Active        string                 `protobuf:"bytes,3,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStatusAsset) Reset() {
	*x = ServiceStatusAsset{}
	mi := &file_asset_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatusAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatusAsset) ProtoMessage() {}

func (x *ServiceStatusAsset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatusAsset.ProtoReflect.Descriptor instead.
func (*ServiceStatusAsset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{21}
}

func (x *ServiceStatusAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceStatusAsset) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ServiceStatusAsset) GetActive() string {
	if x != nil {
		return x.Active
	}
	return ""
}

// ---- Web 组件 ----
type WebComponentAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	BasePath      string                 `protobuf:"bytes,4,opt,name=base_path,json=basePath,proto3" json:"base_path,omitempty"`
	ConfigPath    string                 `protobuf:"bytes,5,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	Pid           int32                  `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebComponentAsset) Reset() {
	*x = WebComponentAsset{}
	mi := &file_asset_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebComponentAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebComponentAsset) ProtoMessage() {}

func (x *WebComponentAsset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebComponentAsset.ProtoReflect.Descriptor instead.
func (*WebComponentAsset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{22}
}

func (x *WebComponentAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WebComponentAsset) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WebComponentAsset) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *WebComponentAsset) GetBasePath() string {
	if x != nil {
		return x.BasePath
	}
	return ""
}

func (x *WebComponentAsset) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *WebComponentAsset) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type WebComponentReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	WebComponents []*WebComponentAsset   `protobuf:"bytes,2,rep,name=web_components,json=webComponents,proto3" json:"web_components,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebComponentReport) Reset() {
	*x = WebComponentReport{}
	mi := &file_asset_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebComponentReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebComponentReport) ProtoMessage() {}

func (x *WebComponentReport) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebComponentReport.ProtoReflect.Descriptor instead.
func (*WebComponentReport) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{23}
}

func (x *WebComponentReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *WebComponentReport) GetWebComponents() []*WebComponentAsset {
	if x != nil {
		return x.WebComponents
	}
	return nil
}

// ---- 硬件 ----
type HardwareAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manufacturer  string                 `protobuf:"bytes,1,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,3,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Uuid          string                 `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	BootTime      string                 `protobuf:"bytes,5,opt,name=boot_time,json=bootTime,proto3" json:"boot_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HardwareAsset) Reset() {
	*x = HardwareAsset{}
	mi := &file_asset_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareAsset) ProtoMessage() {}

func (x *HardwareAsset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareAsset.ProtoReflect.Descriptor instead.
func (*HardwareAsset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{24}
}

func (x *HardwareAsset) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *HardwareAsset) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *HardwareAsset) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *HardwareAsset) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *HardwareAsset) GetBootTime() string {
	if x != nil {
		return x.BootTime
	}
	return ""
}

type HardwareReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hardware      *HardwareAsset         `protobuf:"bytes,2,opt,name=hardware,proto3" json:"hardware,omitempty"`
	KernelModules []*KernelModuleAsset   `protobuf:"bytes,3,rep,name=kernel_modules,json=kernelModules,proto3" json:"kernel_modules,omitempty"`
	EnvVariables  []*EnvVariableAsset    `protobuf:"bytes,4,rep,name=env_variables,json=envVariables,proto3" json:"env_variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HardwareReport) Reset() {
	*x = HardwareReport{}
	mi := &file_asset_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareReport) ProtoMessage() {}

func (x *HardwareReport) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareReport.ProtoReflect.Descriptor instead.
func (*HardwareReport) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{25}
}

func (x *HardwareReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HardwareReport) GetHardware() *HardwareAsset {
	if x != nil {
		return x.Hardware
	}
	return nil
}

func (x *HardwareReport) GetKernelModules() []*KernelModuleAsset {
	if x != nil {
		return x.KernelModules
	}
	return nil
}

func (x *HardwareReport) GetEnvVariables() []*EnvVariableAsset {
	if x != nil {
		return x.EnvVariables
	}
	return nil
}

type KernelModuleAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Size          string                 `protobuf:"bytes,5,opt,name=size,proto3" json:"size,omitempty"`
	UsedBy        int32                  `protobuf:"varint,6,opt,name=used_by,json=usedBy,proto3" json:"used_by,omitempty"`
	Parameters    []string               `protobuf:"bytes,7,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KernelModuleAsset) Reset() {
	*x = KernelModuleAsset{}
	mi := &file_asset_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelModuleAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelModuleAsset) ProtoMessage() {}

func (x *KernelModuleAsset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelModuleAsset.ProtoReflect.Descriptor instead.
func (*KernelModuleAsset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{26}
}

func (x *KernelModuleAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KernelModuleAsset) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KernelModuleAsset) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *KernelModuleAsset) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *KernelModuleAsset) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *KernelModuleAsset) GetUsedBy() int32 {
	if x != nil {
		return x.UsedBy
	}
	return 0
}

func (x *KernelModuleAsset) GetParameters() []string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type EnvVariableAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	User          string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvVariableAsset) Reset() {
	*x = EnvVariableAsset{}
	mi := &file_asset_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVariableAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVariableAsset) ProtoMessage() {}

func (x *EnvVariableAsset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVariableAsset.ProtoReflect.Descriptor instead.
func (*EnvVariableAsset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{27}
}

func (x *EnvVariableAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvVariableAsset) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *EnvVariableAsset) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EnvVariableAsset) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

// ---- 网络 ----
type NetworkGatewayAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gateway       string                 `protobuf:"bytes,1,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Dns           []string               `protobuf:"bytes,2,rep,name=dns,proto3" json:"dns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkGatewayAsset) Reset() {
	*x = NetworkGatewayAsset{}
	mi := &file_asset_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkGatewayAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkGatewayAsset) ProtoMessage() {}

func (x *NetworkGatewayAsset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkGatewayAsset.ProtoReflect.Descriptor instead.
func (*NetworkGatewayAsset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{28}
}

func (x *NetworkGatewayAsset) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *NetworkGatewayAsset) GetDns() []string {
	if x != nil {
		return x.Dns
	}
	return nil
}

type NetworkDetailAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mac           string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	Ips           []string               `protobuf:"bytes,3,rep,name=ips,proto3" json:"ips,omitempty"`
	Speed         string                 `protobuf:"bytes,4,opt,name=speed,proto3" json:"speed,omitempty"`
	Duplex        string                 `protobuf:"bytes,5,opt,name=duplex,proto3" json:"duplex,omitempty"`
	Mtu           string                 `protobuf:"bytes,6,opt,name=mtu,proto3" json:"mtu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkDetailAsset) Reset() {
	*x = NetworkDetailAsset{}
	mi := &file_asset_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkDetailAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkDetailAsset) ProtoMessage() {}

func (x *NetworkDetailAsset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkDetailAsset.ProtoReflect.Descriptor instead.
func (*NetworkDetailAsset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{29}
}

func (x *NetworkDetailAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkDetailAsset) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *NetworkDetailAsset) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *NetworkDetailAsset) GetSpeed() string {
	if x != nil {
		return x.Speed
	}
	return ""
}

func (x *NetworkDetailAsset) GetDuplex() string {
	if x != nil {
		return x.Duplex
	}
	return ""
}

func (x *NetworkDetailAsset) GetMtu() string {
	if x != nil {
		return x.Mtu
	}
	return ""
}

type NetworkReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	GatewayDns     *NetworkGatewayAsset   `protobuf:"bytes,2,opt,name=gateway_dns,json=gatewayDns,proto3" json:"gateway_dns,omitempty"`
	NetworkDetails []*NetworkDetailAsset  `protobuf:"bytes,3,rep,name=network_details,json=networkDetails,proto3" json:"network_details,omitempty"`
	DiskUsages     []*DiskUsageAsset      `protobuf:"bytes,4,rep,name=disk_usages,json=diskUsages,proto3" json:"disk_usages,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NetworkReport) Reset() {
	*x = NetworkReport{}
	mi := &file_asset_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkReport) ProtoMessage() {}

func (x *NetworkReport) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkReport.ProtoReflect.Descriptor instead.
func (*NetworkReport) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{30}
}

func (x *NetworkReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *NetworkReport) GetGatewayDns() *NetworkGatewayAsset {
	if x != nil {
		return x.GatewayDns
	}
	return nil
}

func (x *NetworkReport) GetNetworkDetails() []*NetworkDetailAsset {
	if x != nil {
		return x.NetworkDetails
	}
	return nil
}

func (x *NetworkReport) GetDiskUsages() []*DiskUsageAsset {
	if x != nil {
		return x.DiskUsages
	}
	return nil
}

type DiskUsageAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountPoint    string                 `protobuf:"bytes,1,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	TotalMb       int32                  `protobuf:"varint,2,opt,name=total_mb,json=totalMb,proto3" json:"total_mb,omitempty"`
	UsedMb        int32                  `protobuf:"varint,3,opt,name=used_mb,json=usedMb,proto3" json:"used_mb,omitempty"`
	UsePercent    string                 `protobuf:"bytes,4,opt,name=use_percent,json=usePercent,proto3" json:"use_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskUsageAsset) Reset() {
	*x = DiskUsageAsset{}
	mi := &file_asset_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskUsageAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskUsageAsset) ProtoMessage() {}

func (x *DiskUsageAsset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskUsageAsset.ProtoReflect.Descriptor instead.
func (*DiskUsageAsset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{31}
}

func (x *DiskUsageAsset) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *DiskUsageAsset) GetTotalMb() int32 {
	if x != nil {
		return x.TotalMb
	}
	return 0
}

func (x *DiskUsageAsset) GetUsedMb() int32 {
	if x != nil {
		return x.UsedMb
	}
	return 0
}

func (x *DiskUsageAsset) GetUsePercent() string {
	if x != nil {
		return x.UsePercent
	}
	return ""
}

// ---- 性能 ----
type PerfDataAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemPercent    float64                `protobuf:"fixed64,2,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	MemUsedMb     int32                  `protobuf:"varint,3,opt,name=mem_used_mb,json=memUsedMb,proto3" json:"mem_used_mb,omitempty"`
	MemTotalMb    int32                  `protobuf:"varint,4,opt,name=mem_total_mb,json=memTotalMb,proto3" json:"mem_total_mb,omitempty"`
	DiskUsage     []*DiskPerfAsset       `protobuf:"bytes,5,rep,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerfDataAsset) Reset() {
	*x = PerfDataAsset{}
	mi := &file_asset_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerfDataAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerfDataAsset) ProtoMessage() {}

func (x *PerfDataAsset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerfDataAsset.ProtoReflect.Descriptor instead.
func (*PerfDataAsset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{32}
}

func (x *PerfDataAsset) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *PerfDataAsset) GetMemPercent() float64 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *PerfDataAsset) GetMemUsedMb() int32 {
	if x != nil {
		return x.MemUsedMb
	}
	return 0
}

func (x *PerfDataAsset) GetMemTotalMb() int32 {
	if x != nil {
		return x.MemTotalMb
	}
	return 0
}

func (x *PerfDataAsset) GetDiskUsage() []*DiskPerfAsset {
	if x != nil {
		return x.DiskUsage
	}
	return nil
}

type DiskPerfAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountPoint    string                 `protobuf:"bytes,1,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	UsedMb        int32                  `protobuf:"varint,2,opt,name=used_mb,json=usedMb,proto3" json:"used_mb,omitempty"`
	TotalMb       int32                  `protobuf:"varint,3,opt,name=total_mb,json=totalMb,proto3" json:"total_mb,omitempty"`
	Percent       string                 `protobuf:"bytes,4,opt,name=percent,proto3" json:"percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskPerfAsset) Reset() {
	*x = DiskPerfAsset{}
	mi := &file_asset_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskPerfAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskPerfAsset) ProtoMessage() {}

func (x *DiskPerfAsset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskPerfAsset.ProtoReflect.Descriptor instead.
func (*DiskPerfAsset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{33}
}

func (x *DiskPerfAsset) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *DiskPerfAsset) GetUsedMb() int32 {
	if x != nil {
		return x.UsedMb
	}
	return 0
}

func (x *DiskPerfAsset) GetTotalMb() int32 {
	if x != nil {
		return x.TotalMb
	}
	return 0
}

func (x *DiskPerfAsset) GetPercent() string {
	if x != nil {
		return x.Percent
	}
	return ""
}

type PerfReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Perf          *PerfDataAsset         `protobuf:"bytes,2,opt,name=perf,proto3" json:"perf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerfReport) Reset() {
	*x = PerfReport{}
	mi := &file_asset_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerfReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerfReport) ProtoMessage() {}

func (x *PerfReport) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerfReport.ProtoReflect.Descriptor instead.
func (*PerfReport) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{34}
}

func (x *PerfReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PerfReport) GetPerf() *PerfDataAsset {
	if x != nil {
		return x.Perf
	}
	return nil
}

// ---- Agent 自信息 ----
type AgentSelfAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstallPath   string                 `protobuf:"bytes,1,opt,name=install_path,json=installPath,proto3" json:"install_path,omitempty"`
	ConfigPath    string                 `protobuf:"bytes,2,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	LogPath       string                 `protobuf:"bytes,3,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"`
	RunUser       string                 `protobuf:"bytes,4,opt,name=run_user,json=runUser,proto3" json:"run_user,omitempty"`
	RunPid        int32                  `protobuf:"varint,5,opt,name=run_pid,json=runPid,proto3" json:"run_pid,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSelfAsset) Reset() {
	*x = AgentSelfAsset{}
	mi := &file_asset_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSelfAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSelfAsset) ProtoMessage() {}

func (x *AgentSelfAsset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSelfAsset.ProtoReflect.Descriptor instead.
func (*AgentSelfAsset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{35}
}

func (x *AgentSelfAsset) GetInstallPath() string {
	if x != nil {
		return x.InstallPath
	}
	return ""
}

func (x *AgentSelfAsset) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *AgentSelfAsset) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

func (x *AgentSelfAsset) GetRunUser() string {
	if x != nil {
		return x.RunUser
	}
	return ""
}

func (x *AgentSelfAsset) GetRunPid() int32 {
	if x != nil {
		return x.RunPid
	}
	return 0
}

func (x *AgentSelfAsset) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type AgentSelfReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentSelf     *AgentSelfAsset        `protobuf:"bytes,2,opt,name=agent_self,json=agentSelf,proto3" json:"agent_self,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSelfReport) Reset() {
	*x = AgentSelfReport{}
	mi := &file_asset_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSelfReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSelfReport) ProtoMessage() {}

func (x *AgentSelfReport) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSelfReport.ProtoReflect.Descriptor instead.
func (*AgentSelfReport) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{36}
}

func (x *AgentSelfReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentSelfReport) GetAgentSelf() *AgentSelfAsset {
	if x != nil {
		return x.AgentSelf
	}
	return nil
}

var File_asset_proto protoreflect.FileDescriptor

const file_asset_proto_rawDesc = "" +
	"\n" +
	"\vasset.proto\x12\bsentinel\x1a\fcommon.proto\"\xef\x01\n" +
	"\fProcessAsset\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04ppid\x18\x02 \x01(\x05R\x04ppid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\acmdline\x18\x04 \x01(\tR\acmdline\x12\x19\n" +
	"\bexe_path\x18\x05 \x01(\tR\aexePath\x12\x12\n" +
	"\x04user\x18\x06 \x01(\tR\x04user\x12\x14\n" +
	"\x05state\x18\a \x01(\tR\x05state\x12'\n" +
	"\x0flistening_ports\x18\b \x03(\tR\x0elisteningPorts\x12\x1d\n" +
	"\n" +
	"start_time\x18\t \x01(\tR\tstartTime\"`\n" +
	"\rProcessReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x124\n" +
	"\tprocesses\x18\x02 \x03(\v2\x16.sentinel.ProcessAssetR\tprocesses\"\xaa\x02\n" +
	"\tUserAsset\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x05R\x03uid\x12\x10\n" +
	"\x03gid\x18\x03 \x01(\x05R\x03gid\x12\x12\n" +
	"\x04home\x18\x04 \x01(\tR\x04home\x12\x14\n" +
	"\x05shell\x18\x05 \x01(\tR\x05shell\x12\x1b\n" +
	"\thas_shell\x18\x06 \x01(\bR\bhasShell\x12\x17\n" +
	"\ais_root\x18\a \x01(\bR\x06isRoot\x12\x1f\n" +
	"\vis_disabled\x18\b \x01(\bR\n" +
	"isDisabled\x12\x19\n" +
	"\bhas_sudo\x18\t \x01(\bR\ahasSudo\x12\x1d\n" +
	"\n" +
	"last_login\x18\n" +
	" \x01(\tR\tlastLogin\x12\"\n" +
	"\rlast_login_ip\x18\v \x01(\tR\vlastLoginIp\"R\n" +
	"\n" +
	"UserReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12)\n" +
	"\x05users\x18\x02 \x03(\v2\x13.sentinel.UserAssetR\x05users\"\xf3\x02\n" +
	"\vSystemAsset\x12!\n" +
	"\x02os\x18\x01 \x01(\v2\x11.sentinel.OSAssetR\x02os\x12$\n" +
	"\x03cpu\x18\x02 \x01(\v2\x12.sentinel.CPUAssetR\x03cpu\x12-\n" +
	"\x06memory\x18\x03 \x01(\v2\x15.sentinel.MemoryAssetR\x06memory\x12)\n" +
	"\x05disks\x18\x04 \x03(\v2\x13.sentinel.DiskAssetR\x05disks\x122\n" +
	"\bnetworks\x18\x05 \x03(\v2\x16.sentinel.NetworkAssetR\bnetworks\x12%\n" +
	"\x0ekernel_modules\x18\x06 \x03(\tR\rkernelModules\x122\n" +
	"\bservices\x18\a \x03(\v2\x16.sentinel.ServiceAssetR\bservices\x12\x16\n" +
	"\x06locale\x18\b \x01(\tR\x06locale\x12\x1a\n" +
	"\btimezone\x18\t \x01(\tR\btimezone\"O\n" +
	"\aOSAsset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06kernel\x18\x03 \x01(\tR\x06kernel\"6\n" +
	"\bCPUAsset\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x14\n" +
	"\x05cores\x18\x02 \x01(\x05R\x05cores\"L\n" +
	"\vMemoryAsset\x12\x19\n" +
	"\btotal_mb\x18\x01 \x01(\x05R\atotalMb\x12\"\n" +
	"\rswap_total_mb\x18\x02 \x01(\x05R\vswapTotalMb\"g\n" +
	"\tDiskAsset\x12\x1f\n" +
	"\vmount_point\x18\x01 \x01(\tR\n" +
	"mountPoint\x12\x1e\n" +
	"\n" +
	"filesystem\x18\x02 \x01(\tR\n" +
	"filesystem\x12\x19\n" +
	"\btotal_mb\x18\x03 \x01(\x05R\atotalMb\"F\n" +
	"\fNetworkAsset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\x12\x10\n" +
	"\x03ips\x18\x03 \x03(\tR\x03ips\"<\n" +
	"\fServiceAsset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"X\n" +
	"\fSystemReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12-\n" +
	"\x06system\x18\x02 \x01(\v2\x15.sentinel.SystemAssetR\x06system\"o\n" +
	"\fPackageAsset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x18\n" +
	"\amanager\x18\x03 \x01(\tR\amanager\x12\x17\n" +
	"\asize_kb\x18\x04 \x01(\x03R\x06sizeKb\"\xa1\x02\n" +
	"\rPackageReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x122\n" +
	"\bpackages\x18\x02 \x03(\v2\x16.sentinel.PackageAssetR\bpackages\x12<\n" +
	"\fjar_packages\x18\x03 \x03(\v2\x19.sentinel.JarPackageAssetR\vjarPackages\x12E\n" +
	"\x0fpython_packages\x18\x04 \x03(\v2\x1c.sentinel.PythonPackageAssetR\x0epythonPackages\x12<\n" +
	"\fnpm_packages\x18\x05 \x03(\v2\x19.sentinel.NpmPackageAssetR\vnpmPackages\"\x87\x01\n" +
	"\x0fJarPackageAsset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"executable\x18\x03 \x01(\bR\n" +
	"executable\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\"l\n" +
	"\x12PythonPackageAsset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\"i\n" +
	"\x0fNpmPackageAsset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\"m\n" +
	"\tCronAsset\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1a\n" +
	"\bschedule\x18\x02 \x01(\tR\bschedule\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"R\n" +
	"\n" +
	"CronReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12)\n" +
	"\x05crons\x18\x02 \x03(\v2\x13.sentinel.CronAssetR\x05crons\"\xc4\x01\n" +
	"\x11IdentifiedService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\x05R\x03pid\x12\x19\n" +
	"\bexe_path\x18\x05 \x01(\tR\aexePath\x12\x1f\n" +
	"\vconfig_path\x18\x06 \x01(\tR\n" +
	"configPath\x12\x1f\n" +
	"\vlisten_port\x18\a \x03(\tR\n" +
	"listenPort\"\xa8\x01\n" +
	"\rServiceReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x127\n" +
	"\bservices\x18\x02 \x03(\v2\x1b.sentinel.IdentifiedServiceR\bservices\x12C\n" +
	"\x0eservice_status\x18\x03 \x03(\v2\x1c.sentinel.ServiceStatusAssetR\rserviceStatus\"Z\n" +
	"\x12ServiceStatusAsset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12\x16\n" +
	"\x06active\x18\x03 \x01(\tR\x06active\"\xa5\x01\n" +
	"\x11WebComponentAsset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1b\n" +
	"\tbase_path\x18\x04 \x01(\tR\bbasePath\x12\x1f\n" +
	"\vconfig_path\x18\x05 \x01(\tR\n" +
	"configPath\x12\x10\n" +
	"\x03pid\x18\x06 \x01(\x05R\x03pid\"s\n" +
	"\x12WebComponentReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12B\n" +
	"\x0eweb_components\x18\x02 \x03(\v2\x1b.sentinel.WebComponentAssetR\rwebComponents\"\x9f\x01\n" +
	"\rHardwareAsset\x12\"\n" +
	"\fmanufacturer\x18\x01 \x01(\tR\fmanufacturer\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12#\n" +
	"\rserial_number\x18\x03 \x01(\tR\fserialNumber\x12\x12\n" +
	"\x04uuid\x18\x04 \x01(\tR\x04uuid\x12\x1b\n" +
	"\tboot_time\x18\x05 \x01(\tR\bbootTime\"\xe5\x01\n" +
	"\x0eHardwareReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x123\n" +
	"\bhardware\x18\x02 \x01(\v2\x17.sentinel.HardwareAssetR\bhardware\x12B\n" +
	"\x0ekernel_modules\x18\x03 \x03(\v2\x1b.sentinel.KernelModuleAssetR\rkernelModules\x12?\n" +
	"\renv_variables\x18\x04 \x03(\v2\x1a.sentinel.EnvVariableAssetR\fenvVariables\"\xc4\x01\n" +
	"\x11KernelModuleAsset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x12\n" +
	"\x04size\x18\x05 \x01(\tR\x04size\x12\x17\n" +
	"\aused_by\x18\x06 \x01(\x05R\x06usedBy\x12\x1e\n" +
	"\n" +
	"parameters\x18\a \x03(\tR\n" +
	"parameters\"d\n" +
	"\x10EnvVariableAsset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\"A\n" +
	"\x13NetworkGatewayAsset\x12\x18\n" +
	"\agateway\x18\x01 \x01(\tR\agateway\x12\x10\n" +
	"\x03dns\x18\x02 \x03(\tR\x03dns\"\x8c\x01\n" +
	"\x12NetworkDetailAsset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\x12\x10\n" +
	"\x03ips\x18\x03 \x03(\tR\x03ips\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\tR\x05speed\x12\x16\n" +
	"\x06duplex\x18\x05 \x01(\tR\x06duplex\x12\x10\n" +
	"\x03mtu\x18\x06 \x01(\tR\x03mtu\"\xec\x01\n" +
	"\rNetworkReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12>\n" +
	"\vgateway_dns\x18\x02 \x01(\v2\x1d.sentinel.NetworkGatewayAssetR\n" +
	"gatewayDns\x12E\n" +
	"\x0fnetwork_details\x18\x03 \x03(\v2\x1c.sentinel.NetworkDetailAssetR\x0enetworkDetails\x129\n" +
	"\vdisk_usages\x18\x04 \x03(\v2\x18.sentinel.DiskUsageAssetR\n" +
	"diskUsages\"\x86\x01\n" +
	"\x0eDiskUsageAsset\x12\x1f\n" +
	"\vmount_point\x18\x01 \x01(\tR\n" +
	"mountPoint\x12\x19\n" +
	"\btotal_mb\x18\x02 \x01(\x05R\atotalMb\x12\x17\n" +
	"\aused_mb\x18\x03 \x01(\x05R\x06usedMb\x12\x1f\n" +
	"\vuse_percent\x18\x04 \x01(\tR\n" +
	"usePercent\"\xcb\x01\n" +
	"\rPerfDataAsset\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\x02 \x01(\x01R\n" +
	"memPercent\x12\x1e\n" +
	"\vmem_used_mb\x18\x03 \x01(\x05R\tmemUsedMb\x12 \n" +
	"\fmem_total_mb\x18\x04 \x01(\x05R\n" +
	"memTotalMb\x126\n" +
	"\n" +
	"disk_usage\x18\x05 \x03(\v2\x17.sentinel.DiskPerfAssetR\tdiskUsage\"~\n" +
	"\rDiskPerfAsset\x12\x1f\n" +
	"\vmount_point\x18\x01 \x01(\tR\n" +
	"mountPoint\x12\x17\n" +
	"\aused_mb\x18\x02 \x01(\x05R\x06usedMb\x12\x19\n" +
	"\btotal_mb\x18\x03 \x01(\x05R\atotalMb\x12\x18\n" +
	"\apercent\x18\x04 \x01(\tR\apercent\"T\n" +
	"\n" +
	"PerfReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12+\n" +
	"\x04perf\x18\x02 \x01(\v2\x17.sentinel.PerfDataAssetR\x04perf\"\xbd\x01\n" +
	"\x0eAgentSelfAsset\x12!\n" +
	"\finstall_path\x18\x01 \x01(\tR\vinstallPath\x12\x1f\n" +
	"\vconfig_path\x18\x02 \x01(\tR\n" +
	"configPath\x12\x19\n" +
	"\blog_path\x18\x03 \x01(\tR\alogPath\x12\x19\n" +
	"\brun_user\x18\x04 \x01(\tR\arunUser\x12\x17\n" +
	"\arun_pid\x18\x05 \x01(\x05R\x06runPid\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\"e\n" +
	"\x0fAgentSelfReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x127\n" +
	"\n" +
	"agent_self\x18\x02 \x01(\v2\x18.sentinel.AgentSelfAssetR\tagentSelfB.Z,github.com/CoderXinNing/ebpf-system/proto/pbb\x06proto3"

var (
	file_asset_proto_rawDescOnce sync.Once
	file_asset_proto_rawDescData []byte
)

func file_asset_proto_rawDescGZIP() []byte {
	file_asset_proto_rawDescOnce.Do(func() {
		file_asset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_asset_proto_rawDesc), len(file_asset_proto_rawDesc)))
	})
	return file_asset_proto_rawDescData
}

var file_asset_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_asset_proto_goTypes = []any{
	(*ProcessAsset)(nil),        // 0: sentinel.ProcessAsset
	(*ProcessReport)(nil),       // 1: sentinel.ProcessReport
	(*UserAsset)(nil),           // 2: sentinel.UserAsset
	(*UserReport)(nil),          // 3: sentinel.UserReport
	(*SystemAsset)(nil),         // 4: sentinel.SystemAsset
	(*OSAsset)(nil),             // 5: sentinel.OSAsset
	(*CPUAsset)(nil),            // 6: sentinel.CPUAsset
	(*MemoryAsset)(nil),         // 7: sentinel.MemoryAsset
	(*DiskAsset)(nil),           // 8: sentinel.DiskAsset
	(*NetworkAsset)(nil),        // 9: sentinel.NetworkAsset
	(*ServiceAsset)(nil),        // 10: sentinel.ServiceAsset
	(*SystemReport)(nil),        // 11: sentinel.SystemReport
	(*PackageAsset)(nil),        // 12: sentinel.PackageAsset
	(*PackageReport)(nil),       // 13: sentinel.PackageReport
	(*JarPackageAsset)(nil),     // 14: sentinel.JarPackageAsset
	(*PythonPackageAsset)(nil),  // 15: sentinel.PythonPackageAsset
	(*NpmPackageAsset)(nil),     // 16: sentinel.NpmPackageAsset
	(*CronAsset)(nil),           // 17: sentinel.CronAsset
	(*CronReport)(nil),          // 18: sentinel.CronReport
	(*IdentifiedService)(nil),   // 19: sentinel.IdentifiedService
	(*ServiceReport)(nil),       // 20: sentinel.ServiceReport
	(*ServiceStatusAsset)(nil),  // 21: sentinel.ServiceStatusAsset
	(*WebComponentAsset)(nil),   // 22: sentinel.WebComponentAsset
	(*WebComponentReport)(nil),  // 23: sentinel.WebComponentReport
	(*HardwareAsset)(nil),       // 24: sentinel.HardwareAsset
	(*HardwareReport)(nil),      // 25: sentinel.HardwareReport
	(*KernelModuleAsset)(nil),   // 26: sentinel.KernelModuleAsset
	(*EnvVariableAsset)(nil),    // 27: sentinel.EnvVariableAsset
	(*NetworkGatewayAsset)(nil), // 28: sentinel.NetworkGatewayAsset
	(*NetworkDetailAsset)(nil),  // 29: sentinel.NetworkDetailAsset
	(*NetworkReport)(nil),       // 30: sentinel.NetworkReport
	(*DiskUsageAsset)(nil),      // 31: sentinel.DiskUsageAsset
	(*PerfDataAsset)(nil),       // 32: sentinel.PerfDataAsset
	(*DiskPerfAsset)(nil),       // 33: sentinel.DiskPerfAsset
	(*PerfReport)(nil),          // 34: sentinel.PerfReport
	(*AgentSelfAsset)(nil),      // 35: sentinel.AgentSelfAsset
	(*AgentSelfReport)(nil),     // 36: sentinel.AgentSelfReport
}
var file_asset_proto_depIdxs = []int32{
	0,  // 0: sentinel.ProcessReport.processes:type_name -> sentinel.ProcessAsset
	2,  // 1: sentinel.UserReport.users:type_name -> sentinel.UserAsset
	5,  // 2: sentinel.SystemAsset.os:type_name -> sentinel.OSAsset
	6,  // 3: sentinel.SystemAsset.cpu:type_name -> sentinel.CPUAsset
	7,  // 4: sentinel.SystemAsset.memory:type_name -> sentinel.MemoryAsset
	8,  // 5: sentinel.SystemAsset.disks:type_name -> sentinel.DiskAsset
	9,  // 6: sentinel.SystemAsset.networks:type_name -> sentinel.NetworkAsset
	10, // 7: sentinel.SystemAsset.services:type_name -> sentinel.ServiceAsset
	4,  // 8: sentinel.SystemReport.system:type_name -> sentinel.SystemAsset
	12, // 9: sentinel.PackageReport.packages:type_name -> sentinel.PackageAsset
	14, // 10: sentinel.PackageReport.jar_packages:type_name -> sentinel.JarPackageAsset
	15, // 11: sentinel.PackageReport.python_packages:type_name -> sentinel.PythonPackageAsset
	16, // 12: sentinel.PackageReport.npm_packages:type_name -> sentinel.NpmPackageAsset
	17, // 13: sentinel.CronReport.crons:type_name -> sentinel.CronAsset
	19, // 14: sentinel.ServiceReport.services:type_name -> sentinel.IdentifiedService
	21, // 15: sentinel.ServiceReport.service_status:type_name -> sentinel.ServiceStatusAsset
	22, // 16: sentinel.WebComponentReport.web_components:type_name -> sentinel.WebComponentAsset
	24, // 17: sentinel.HardwareReport.hardware:type_name -> sentinel.HardwareAsset
	26, // 18: sentinel.HardwareReport.kernel_modules:type_name -> sentinel.KernelModuleAsset
	27, // 19: sentinel.HardwareReport.env_variables:type_name -> sentinel.EnvVariableAsset
	28, // 20: sentinel.NetworkReport.gateway_dns:type_name -> sentinel.NetworkGatewayAsset
	29, // 21: sentinel.NetworkReport.network_details:type_name -> sentinel.NetworkDetailAsset
	31, // 22: sentinel.NetworkReport.disk_usages:type_name -> sentinel.DiskUsageAsset
	33, // 23: sentinel.PerfDataAsset.disk_usage:type_name -> sentinel.DiskPerfAsset
	32, // 24: sentinel.PerfReport.perf:type_name -> sentinel.PerfDataAsset
	35, // 25: sentinel.AgentSelfReport.agent_self:type_name -> sentinel.AgentSelfAsset
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_asset_proto_init() }
func file_asset_proto_init() {
	if File_asset_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_asset_proto_rawDesc), len(file_asset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_asset_proto_goTypes,
		DependencyIndexes: file_asset_proto_depIdxs,
		MessageInfos:      file_asset_proto_msgTypes,
	}.Build()
	File_asset_proto = out.File
	file_asset_proto_goTypes = nil
	file_asset_proto_depIdxs = nil
}
