[agent]
name = ""
server = "127.0.0.1:50051"
retry_delay = "5s"
heartbeat_interval = "10s"
collect_interval = "300s"

[[autoload]]
name = "exec_monitor"
id = "auto-exec-001"
enabled = true
remove = true
path = "probes/templates/exec_monitor_ebpf/exec_monitor.o"

[[autoload]]
name = "bash_monitor"
id = "auto-bash-001"
enabled = true
remove = true
path = "probes/templates/bash_monitor/bash_monitor.o"

[[autoload]]
name = "tcp_monitor"
id = "auto-tcp-001"
enabled = true
remove = true
path = "probes/templates/tcp_monitor/tcp_monitor.o"

[xdp]
enabled = true
iface = "ens33"
server_ip = "172.16.2.141"
server_port = 9999
