// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package exec_monitor

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadExec_monitor returns the embedded CollectionSpec for exec_monitor.
func loadExec_monitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Exec_monitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load exec_monitor: %w", err)
	}

	return spec, err
}

// loadExec_monitorObjects loads exec_monitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*exec_monitorObjects
//	*exec_monitorPrograms
//	*exec_monitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadExec_monitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadExec_monitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// exec_monitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type exec_monitorSpecs struct {
	exec_monitorProgramSpecs
	exec_monitorMapSpecs
	exec_monitorVariableSpecs
}

// exec_monitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type exec_monitorProgramSpecs struct {
	TraceExecve *ebpf.ProgramSpec `ebpf:"trace_execve"`
}

// exec_monitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type exec_monitorMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// exec_monitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type exec_monitorVariableSpecs struct {
}

// exec_monitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadExec_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type exec_monitorObjects struct {
	exec_monitorPrograms
	exec_monitorMaps
	exec_monitorVariables
}

func (o *exec_monitorObjects) Close() error {
	return _Exec_monitorClose(
		&o.exec_monitorPrograms,
		&o.exec_monitorMaps,
	)
}

// exec_monitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadExec_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type exec_monitorMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *exec_monitorMaps) Close() error {
	return _Exec_monitorClose(
		m.Events,
	)
}

// exec_monitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadExec_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type exec_monitorVariables struct {
}

// exec_monitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadExec_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type exec_monitorPrograms struct {
	TraceExecve *ebpf.Program `ebpf:"trace_execve"`
}

func (p *exec_monitorPrograms) Close() error {
	return _Exec_monitorClose(
		p.TraceExecve,
	)
}

func _Exec_monitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed exec_monitor_bpfel.o
var _Exec_monitorBytes []byte
